### ISSUE TITLE
Bulk insert?

### ISSUE THREAD

**Issue by OneManMobile** [pardom-zz/ActiveAndroid#1]
Can this library support androids faster "Bulk insert", where you create an array of items and save them all in one function call?

**Comment by pardom-zz** [comment]
You  can do this with transactions. In my testing, calls wrapped in transactions are sped up by a factor of around 100. Here's an example:

``` java
ActiveAndroid.beginTransaction();
for (int i = 0; i < 100; i++) {
    Foo foo = new Foo();
    foo.name = "Foo " + i;
    foo.save()
}
ActiveAndroid.setTransactionSuccessful();
ActiveAndroid.endTransaction();
```

This takes about 40 ms wrapped in a transaction, and 4 seconds when it's not.

Does this resolve your issue?

**Comment by OneManMobile** [comment]
It sure seems to. Thanks a lot!

I would recommend highlighting this in the documentation, as bulk insert is widely used when creating Android apps that synchronizes against webservices.

Again, thank you.

**Comment by pardom-zz** [comment]
You're welcome. The documentation is still missing some things, and this is one of them.

**Comment by sergiocampama** [comment]
What can you do to avoid BEGIN EXCLUSIVE errors? Sometimes beginTransaction fails with this error: `android.database.sqlite.SQLiteException: database is locked: BEGIN EXCLUSIVE`

Is there a way to test if there if the database is locked so I can apply a small delay?
