### ISSUE TITLE
Functions like save, delete must have a valid return type instead of void

### ISSUE THREAD

**Issue by ghost** [pardom-zz/ActiveAndroid#102]
Hi,

I was trying to insert a row in the database table and then i realised that save method doesn't have a return type. One of column in table was "unique" and i was entering a duplicate record so instead of giving me an error.. it was executing the code as if there is no error.

Ideally it should return the the ID of the newly inserted row or the number of rows affected if a whereClause is passed in, 0 otherwise in case of delete... like normal Sqlite Functions.

**Comment by bharathlakshman** [comment]
You might want to read up on Active Records Design Pattern(https://en.wikipedia.org/wiki/Active_record_pattern)

**Comment by leonardoxh** [comment]
When you use the "save" method the ID is stored on mId on the model type, just use getId() and retrieve the new value, in other wise the save will throw a SQLException...
