### ISSUE TITLE
Creating field with byte[]

### ISSUE THREAD

**Issue by davsilvera** [pardom-zz/ActiveAndroid#105]
Good afternoon everyone,

I would like to store a Bitmap on my DataBase. So I convert it on Byte array.

But when I save my object, I see that my field is not created on my table.

I simply create the field like this:

@Column(name = "image")
    public byte[]   image;

What is wrong?

Thank you.

**Comment by leonardoxh** [comment]
Hm, its more useful create a column as a string and get the image from the disk or the web, but in this case I really do no, but for performance prefer save a string in Db and load from disk instead of a blob object.

**Comment by davsilvera** [comment]
Ok thanks.

So we can't save byte array with activeAndroid.

**Comment by pardom-zz** [comment]
AA supports byte arrays. There could be a number of things wrong with your implementation. Can you post more information?

**Comment by davsilvera** [comment]
That is my class:

@Table(name = "Image")
public class Image extends Model
{
    @Column(name = "image")
    public byte[]   image;

```
@Column(name = "type")
public String   type;

@Column(name = "date")
public String   date;
```

}

All field was created like column except my field image.

**Comment by leonardoxh** [comment]
I log this from my console 

08-21 13:05:08.649: V/ActiveAndroid(1511): CREATE TABLE IF NOT EXISTS Image (type TEXT, date TEXT, Id INTEGER PRIMARY KEY AUTOINCREMENT, image BLOB);
08-21 13:05:08.697: I/ActiveAndroid(1511): Foreign Keys supported. Enabling foreign key features.
08-21 13:05:08.697: V/ActiveAndroid(1511): ActiveAndroid initialized successfully.
08-21 13:05:08.709: V/ActiveAndroid(1511): SELECT image FROM Image LIMIT 1  

No exceptions, column founded... I test with a android 4.2 device

**Comment by davsilvera** [comment]
Ok so I don'y know why it doesn't work for me.

Thanks for your help. I think I restart a new project and I retest this.

**Comment by vsigler** [comment]
Just a thought, but did you have the image column there from the start or did you add it later (when the app was already installed/running in your device/emulator). AA will create the initial table, but if you add a field to the model later, you'll have to increment db version and add a migration sql which adds the column.

**Comment by davsilvera** [comment]
I test with removing the database on data/data/myApplicationPackage/databases
