### ISSUE TITLE
How to use Delete with INNER JOIN?

### ISSUE THREAD

**Issue by nologinatgit** [pardom-zz/ActiveAndroid#112]
I have two tables and I want to delete from one of them but I have to filter the referred table.
I tried to use the following code: 

 new Delete().from(Information.class).as("INF").innerJoin(Data1.class).on("Inf_ID=Data_Inf_ID").where("Date>=? AND SubID=?"
              , date1.toString(),sibID).execute();

That was translated to this:
DELETE FROM Information AS INF 
INNER JOIN Data1 ON Inf_ID=Data_Inf_ID WHERE Date>=? AND SubID=?

And I get the following exception:
near "AS": syntax error: , while compiling ...

How could I use the inner join with my delete?

**Comment by vonloxley** [comment]
Don't use .as(). It's not supported in delete statements and should probably trigger an exception anyway. Try to use a "Id in (select Id from ...)" in the where clause.

**Comment by nologinatgit** [comment]
Yeah, I figured it. I eventually created the whole script and used SqlUtils.executeSql to use the delete.
