### ISSUE TITLE
UUID as Primary key possible?

### ISSUE THREAD

**Issue by kramer65** [pardom-zz/ActiveAndroid#115]
For our company we are developing an Android app which will have a rather complex database setup. Looking for an ORM I ran into ActiveAndroid, which looks very promising. 

One thing ActiveAndroid seems to handle automagically though, is the creation of a unique id for every record. For our app we need to have UUIDs as primary key's. Can I override the automagic id and replace it with my unique UUID column?

**Comment by vsigler** [comment]
I don't think there is an easy and quick way to do this. The ID generation is not directly exposed to the user, it is using the auto-increment feature of the sqlite database. So if you want to implement your own ID generator, and bypass the id generation the database does, you'll have to make the necessary edits in the codebase.

What you can do is to add another unique column that would hold your identifier and make queries against it, while keeping the ActiveAndroid's internal ids.

**Comment by pardom-zz** [comment]
This is the next feature to be pushed. The Id column name will be configurable.

**Comment by kramer65** [comment]
Alright, for now I'll use this unique column then. Thanks for the tip!

@pardom 
First of all; thanks for the good work! Second: would you know when this feature will be finished? We're on quite a tight schedule in my company and I would really really like to use ActiveAndroid!
Keep up the good work!

I just see these answers to this question, but in the meantime I already posted a new one (Issue #117 ) regarding the the storage of UUIDs and DateTime objects using ActiveAndroid. Would any of you two know what the usual way is of making models with datatypes not native to SQLite?

**Comment by pardom-zz** [comment]
It's in the testing phase at this moment. I screwed myself by not writing tests early on, so this is always the bottleneck for new features. I'll try to get it out by the end of the week.

**Comment by kramer65** [comment]
@pardom 
Awesome, great to hear that ActiveAndroid is in active development! Do you refer to both UUID as a primary key and being able to define UUIDs/DateTimes in my model? As in: will both these options be supported at the end of the week?

What about a BigDecimal? Do you know how I can define that in my model (unfortunately doubles are not precise enough).

**Comment by kramer65** [comment]
Excuse me to be spamming you guys like this, but I'm under some pressure here. Trying to show how awesome AA (ActiveAndroid) is so that we can start using it in our company instead of building our own horrible DB-code.. :)

So I'm trying to use DateTime in my model. Unfortunately AA seems to refuse to insert DateTime into the DB. Is this a known problem or am I doing something horribly wrong?

**Comment by pardom-zz** [comment]
What DateTime class are you using? SQLite only supports some primitive types, so you have to use a TypeSerializer for non-primitive data structures. Some are included.

https://github.com/pardom/ActiveAndroid/tree/master/src/com/activeandroid/serializer

Based on the class name it sounds like you're using Joda? Take a look at the existing serializers, which convert to/from epoch time.

**Comment by kramer65** [comment]
I'm using the org.joda.time.DateTime class. As far as I understand (from this page: http://sqlite.org/datatype3.html) SQLite supports a form of DateTime so it would be awesome if the joda datetime would be converted to SQLite DateTime and back.

I'll have a look at the class, but I'm not a Java-guru (to say the least). Is there any easy way to do this?

**Comment by pardom-zz** [comment]
SQLite does not have a date/time datatype, however it does have data/time functions. The most common way to store dates is as an epoch timestamp INTEGER. That is, milliseconds since 1/1/1970. DateTime has methods to retrieve this value and create a DateTime object from this value.

**Comment by vonloxley** [comment]
You can copy UtilDateSerializer.java and modify your copy to serialize o.j.t.DateTime. Should be straight forward.

**Comment by pardom-zz** [comment]
You would add this class to your project, not to build it into AA. AA will find it automatically, or preferably you can define the serializers in the configuration or meta-data.

**Comment by kramer65** [comment]
Alright! I created a file called like so: http://pastebin.com/te6dHezm

This works like a charm. With this out of the way, I think I will be able to convince my colleagues. Tomorrow I'll write another one for UUID.

Just one last question; how would you suggest I handle BigDecimal? Which SQLite type would be most suitable?

**Comment by pardom-zz** [comment]
I don't know the inner workings of BigDecimal offhand. Take a look at the source here:
https://android.googlesource.com/platform/libcore/+/refs/heads/master/luni/src/main/java/java/math/BigDecimal.java

**Comment by vonloxley** [comment]
http://developer.android.com/reference/java/math/BigDecimal.html
UnscaledValue() and scale().
http://developer.android.com/reference/java/math/BigInteger.html#intValue%28%29 or toString().

Good luck!

**Comment by kramer65** [comment]
Awesome thanks! Just finished three Serializers for DateTime, BigDecimal and UUID. All works like a charm!

Just a last note to close this issue off; so far I simply love ActiveAndroid. It's everything I hoped ORMLite was.. :)

**Comment by vonloxley** [comment]
Hi @kramer65! It would by nice, if you could make a pull-request with the BigDecimal- and UUID-Serializers as a contribution.

**Comment by kramer65** [comment]
@vonloxley 
I was indeed already planning on that.. :)
I'm not really familiar with this process though. I just tried pushing back with the usual `git push -u mybranch`, but this gets me the following error:

```
You can't push to git://github.com/pardom/ActiveAndroid.git
Use https://github.com/pardom/ActiveAndroid.git
```

I also checked at the pull requests page, but on there it obviously doesn't show me my branch (since I couldn't push back). Could you give me a little tip of how I can contribute this back?

**Comment by intrications** [comment]
@kramer65 

You need to create your own fork of the repo and push to that. Then github will let you create a pull request from your fork.

https://help.github.com/articles/fork-a-repo

**Comment by kramer65** [comment]
@intrications 
Thanks for that. I forked, cloned to my computer, committed changes, pushed back, and created a pull request.

Cheers!
