### ISSUE TITLE
More documentation?

### ISSUE THREAD

**Issue by kramer65** [pardom-zz/ActiveAndroid#116]
So far we really like ActiveAndroid (don't understand why it is not a lot more popular than ORMLite). What I just wondered about is whether there is any more documentation than just the couple links that are in the README.MD?

**Comment by vsigler** [comment]
Not that I know. Most people (at least me) end up just reading the source code. The codebase is not so large, so it's not a big deal. You'll find lots of answers for questions like "why doesn't this work the way I expect?"

**Comment by kramer65** [comment]
Thanks, you are absolutely right. Altgough I still think more extensive docs would be better, a read through the testcases helped a lot!

Cheers!
