### ISSUE TITLE
How to define UUID and DateTime in my ActiveAndroid Model?

### ISSUE THREAD

**Issue by kramer65** [pardom-zz/ActiveAndroid#117]
I've got a model in which I use a UUID and a DateTime like this:

```
@Column(name = "uuid")
public UUID uuid; 

@Column(name = "created")
public DateTime created;

public User(String displayName, String firstName, String lastName){
    super();
    this.uuid = UUID.randomUUID();
    this.created = DateTime.now();
    this.displayName = displayName;
    this.firstName = firstName;
    this.lastName = lastName;
}

public static User userByName(String displayName){
    return new Select().from(User.class).where("displayName = ?", displayName).executeSingle();
}
```

I now try to insert a user and read it back using the following code:

```
User user = new User("myname", "myfirstname", "mylastname");
user.save();

User a = User.userByName("myname");
Log.wtf(a.displayName, a.lastName);
Log.wtf(a.displayName, a.uuid.toString());
```

The displayName and lastName are displayed perfectly well. But the uuid.toString() gives me a NullPointerException. So I suppose ActiveAndroid tries to insert the DateTime and UUID without converting them to string or Timestamp (which SQLite of course doesn't like). I could of course define my uuid as String and my DateTime as Int. But I would really like to keep my uuid a proper UUID instead of defining it as a string in the class so that I can use this model in a proper way in the rest of my code.

Does anybody know how I can solve this?

**Comment by lectricas** [comment]
why the issue is closed? Any solutions?

**Comment by joshuapinter** [comment]
For others, I was trying to use JodaTime's `DateTime` as a column field type as well and without adding a custom Type Serializer for `DateTime`, it would silently not create any columns using `DateTime` types.

Look at my issue here #516 for more information and to give it a thumbs up if you've wasted time on this.
