### ISSUE TITLE
Using a custom model constructor, object is not saved

### ISSUE THREAD

**Issue by blork** [pardom-zz/ActiveAndroid#12]
In a subclass of Model, I have the custom constructor:

```
public User(String username) {
    super();
    this.username = username;
}
```

And I call:

```
User user = new User("test");
user.save();
```

But when I call `new Select().from(User.class).execute()` the resulting list is empty.

On the other hand, doing

```
User user = new User();
user.username = "test";
user.save();
```

and the user is saved and can be retrieved.

Is there a reason I can't have a custom constructor on my Model subclass? What am I missing?

**Comment by pardom-zz** [comment]
ActiveAndroid requires you to implement the default constructor because that's what it uses when populating from a cursor. It's the only constructor signature it can know about for sure.

Implement the default constructor in addition to yours, and it should work.

**Comment by pardom-zz** [comment]
Let me know if I can close this.

**Comment by vidriloco** [comment]
Sorry for re-opening this issue, I do believe this trick should be written in the documentation. I spent almost 2 hours trying to see what was going wrong, I even was searching another library to try or implementing a simple wrapper class. 

Anyway, thanks for this nice piece of software.
