### ISSUE TITLE
Increasing DB version doesn't recreate the DB.

### ISSUE THREAD

**Issue by kramer65** [pardom-zz/ActiveAndroid#122]
I've got a DB table in which I added a column name "requiredAmount". After this I increased the AA_DB_VERSION in the AndroidManifest.xml from 8 to 9. When I run the app on my testing device again and try to insert something in the DB it tells me that the table does not have a column named requiredAmount.

A workaround is renaming the DB into something like "mydb2.db", which simply creates a new database next to the old one including the new table column. This solves my trouble for now, but it's not a realistic option for the rollout of our app.

Would anybody know how I can solve this issue?

**Comment by pardom-zz** [comment]
ActiveAndroid does not modify existing schema, that's left up to migration scripts. ActiveAndroid will, however, add non-existing tables when the database version is incremented. Migration is only required when changing production schema. Learn more about that here:

https://github.com/pardom/ActiveAndroid/wiki/Schema-migrations

If you're still developing your schema, simply clear the data to regenerate the database

```
adb shell pm clear your.package.name
```
