### ISSUE TITLE
How to define the DB name & version in a different place than the Manifest?

### ISSUE THREAD

**Issue by kramer65** [pardom-zz/ActiveAndroid#124]
For various reasons we will be creating multiple databases within the user its phone (one for every user). Is there a way that I can define the DB name and version in a different place than in the Android Manifest?

All tips are welcome! :)

**Comment by xArthasx** [comment]
I think AA doesn't support multiple DB but you can associate things so you should make a model user and associate everything to it.

**Comment by vsigler** [comment]
You cannot have multiple DBs in one application with AA. I'm not even sure how you could reasonably do it with how AA is designed. You would need some sort of a context object that would represent the individual database and somehow associate models with it. Or maybe associate model not only with table name, but also db. That would however pose problems with cross references between models of different dbs, not to mention attempts for joins.

Do the databases have common tables (table names)? If not then maybe you could just merge them into one for AA to use. Then if you need to work with the individual smaller dbs, you would have to import/export/sync them with the "main" database. But it's a very crude solution, plus the syncing could be quite troublesome.

**Comment by kramer65** [comment]
That is a pity to hear. In that case we'll probably use one DB indeed. Since we'll be handling rather sensitive data I'll have to read more on security/encryption features anyway.

Thanks anyway!
