### ISSUE TITLE
Multiple wheres now working

### ISSUE THREAD

**Issue by sergiocampama** [pardom-zz/ActiveAndroid#126]
Hi, 

If I use `Select().from(Dispatch.class).where("Route = ?", this.getId()).where("StatusCode = 0").orderBy("Slot ASC").execute();` 

the first condition is not considered, resulting in all the `Dispatch`es to be returned. In this example, because `StatusCode = 0` has no variables, I can use `return new Select().from(Dispatch.class).where("StatusCode = 0 AND Route = ?", this.getId()).orderBy("Slot ASC").execute();`, but what can I do if I have multiple `where` with variable conditions?

**Comment by okhoshi** [comment]
Simply put another '?' for each other variable condition. E.g: `return new Select().from(Dispatch.class).where("StatusCode = 0 AND Route = ? AND AnotherCondition = ?", this.getId(), this.getSecondCondition()).orderBy("Slot ASC").execute();`

**Comment by sergiocampama** [comment]
Ahh, thank you, didn't notice the second argument was variable...

**Comment by joshuapinter** [comment]
I ran into the same issue, but I would like to chain my `where()` methods. Is that possible?
