### ISSUE TITLE
How to add a new field to an existing table

### ISSUE THREAD

**Issue by wangvsa** [pardom-zz/ActiveAndroid#136]
for example.
I have created a table "Categories"
public class Category extends Model {
    @Column(name="Name")
    public String name;
}

Now i want to add a new field how can i do this?
@Table(name="Categories")
public class Category extends Model {
    @Column(name="Name")
    public String name;
    @Column(name="rate")
    public int rate;
}
 Category category = new Category();
 category.name = "book";
 category.rate = 999;
 category.save();
 category.getId();  // this gives -1

**Comment by vonloxley** [comment]
https://github.com/pardom/ActiveAndroid/wiki/Schema-migrations

**Comment by wangvsa** [comment]
Thank you @vonloxley  i missed this chapter.

**Comment by balazsmaria** [comment]
this is ridiculous if you're app is still under development.
