### ISSUE TITLE
Failed to read row 0

### ISSUE THREAD

**Issue by serkanucar** [pardom-zz/ActiveAndroid#144]
Failed to read row 0, column -1 from a CursorWindow which has 114 rows, 4 columns.
Failed to process cursor.
java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
at com.activeandroid.util.SQLiteUtils.processCursor(SQLiteUtils.java:201)
at com.activeandroid.util.SQLiteUtils.rawQuery(SQLiteUtils.java:93)
at com.activeandroid.query.From.execute(From.java:205)

**Comment by serkanucar** [comment]
I solved the problem. 
In all tables there should be a primary key field with the name  "Id".

**Comment by jackyshan** [comment]
@Table(name = "tablename", id = "id")

add primary id
