### ISSUE TITLE
ActiveAndroid and support library

### ISSUE THREAD

**Issue by rothschild86** [pardom-zz/ActiveAndroid#149]
Not sure what this is about, but I figured I'd post it. I know AA does some reflection on start up when looking for model classes. With the new support library, it seems to get a little overzealous with it.

Everything works fine, but I see a bunch of these on init in my logcat:

11-28 14:14:42.144: E/ActiveAndroid(7361): Couldn't create class.
11-28 14:14:42.144: E/ActiveAndroid(7361): java.lang.ClassNotFoundException: android.support.v4.os.ParcelableCompatCreatorHoneycombMR2

11-28 14:14:42.184: E/ActiveAndroid(7361): Couldn't create class.
11-28 14:14:42.184: E/ActiveAndroid(7361): java.lang.ClassNotFoundException: android.support.v4.view.AccessibilityDelegateCompatIcs$1

11-28 14:17:55.134: E/ActiveAndroid(7912): Couldn't create class.
11-28 14:17:55.134: E/ActiveAndroid(7912): java.lang.ClassNotFoundException: android.support.v7.internal.view.menu.MenuItemWrapperICS$OnActionExpandListenerWrapper

This is just a sample. There are many of them. Any thoughts?

**Comment by rothschild86** [comment]
So I digged deeper into this, and it seems that AA goes thru every dex file in the app dir looking for model classes. That explains why our app starts are so slow - we use about 20 different jars in our project. But all our models are in com.appname.models. I don't know enough about this mechanism, but shouldn't we be able to limit search just to one package?

**Comment by pardom-zz** [comment]
The documentation has not been update yet, however you can drastically reduce load time by declaring the models in your manifest like so

```
<meta-data
    android:name="AA_MODELS"
    android:value=".data.model.Foo, .data.model.Bar, .data.model.FooBar" />
```

**Comment by rothschild86** [comment]
That made a huge difference. Thanks man :)

**Comment by TomaszZGor** [comment]
I have added AA_MODELS section to android manifest file but I still see errors: "Couldn't create class". I looked at the code and see that scanning for model (com.activeandroid.ModelInfo.scanForModel(..)) shouldn't start if AA_MODELS is set properly. Maybe I did a mistake in android:value= ? Can you put down a valid example of android:values ? I suppose that they should started from dot.

**Comment by lkorth** [comment]
@TomaszZGor I had to specify the full name of the models, package and all to get it to work.

``` xml
<meta-data
    android:name="AA_MODELS"
    android:value="com.activeandroid.data.model.Foo, com.activeandroid.data.model.Bar, com.activeandroid.data.model.FooBar" />
```

**Comment by TomaszZGor** [comment]
@lkorth Thank you :)

**Comment by tedzyc** [comment]
is '_' support for scanning?
like below:
<meta-data
    android:name="AA_MODELS"
    android:value="com.activeandroid.data.model._" />

write too many class full path is too long
