### ISSUE TITLE
AA Maintainer.

### ISSUE THREAD

**Issue by joshuapinter** [pardom-zz/ActiveAndroid#150]
Hi Michael, 

First off, great work with AA. I'm excited about what you've done with it and implementing it into our latest Android tablet project. 

Before I do that, can you give me an idea on how active you are in maintaining the library, and if you would be open to having another maintainer on the repo to help close off some of those outstanding issues and pull requests. I see the last commit was about 3 months ago and there are >50 issues (some of which are quick fixes). 

I'm happy to issue pull requests for updates but just getting a feel for how quickly they will be responded to and merged into the main repo. 

Thanks Michael!

Josh

**Comment by blork** [comment]
+1. While @pardom has done some great work with the library, I think it would be good for it to be moved to an organisation, which could have multiple maintainers. It'd take some of the weight off @pardom and hopefully the rate of improvements and changes would increase.

**Comment by vonloxley** [comment]
:+1:
Hi Sam, I’d like you to act as a maintainer.

**Comment by vsigler** [comment]
+1 on that!

I don't want to sound inappropriate or mean (I understand as my free time is also very limited), but in addition to the open issues, the fact that pull requests remain open (neither rejected nor approved) for very long time discourages people from contributing. I think AA would benefit if there were multiple people maintaining it.

**Comment by pardom-zz** [comment]
Hey @joshuapinter thanks for bringing up this suggestion. I've been meaning to bring it up myself, but as with most things, I haven't really had the time. I've previously gone through the commit logs to find a suitable candidate, but have not approached anyone yet.

Any of the following who are interested in helping maintain the project, please PM me:
@blork, @vonloxley, @zach-klippenstein, @SeanPONeil

**Comment by joshuapinter** [comment]
Hi guys, any word on getting one or more additional maintainers on board? There's some juicy pull requests just waiting to be merged. :)

**Comment by zach-klippenstein** [comment]
I'll have to pass, I unfortunately don't have the time now that I've graduated.

**Comment by SeanPONeil** [comment]
Hey guys,

@pardom gave me push access to ActiveAndroid, so I'll be reviewing pull requests and doing general project maintenance from here on out. Feel free to email me if you have any questions!

**Comment by joshuapinter** [comment]
This is great news. Thanks for stepping up @SeanPONeil, and thanks for sharing push access @pardom.
