### ISSUE TITLE
Fetch id automatically

### ISSUE THREAD

**Issue by vonloxley** [pardom-zz/ActiveAndroid#16]
If I do a

``` java
new Select("name").from(Item.class).orderBy("name").execute();
```

the resulting objects have their id-member set to null and even `getId()` returns null.

Since the id-field is handled by the library I’d expect the call to getId() to succeed, even if I didn’t  specify id in the select-list. Perhaps the id-field should be added to the projection automatically.

**Comment by pardom-zz** [comment]
This is already a feature. Could you post more information to help diagnose the issue? Is it possible that you're not calling _save()_ on the model object?

**Comment by vonloxley** [comment]
Please see `testGetIdAfterSaveAndSelect` in vonloxley/ActiveAndroid@54ed476c3117907c74358a34419a00ab129b8058

I put the hole test-case into my "test_id_select"-branch:
https://github.com/vonloxley/ActiveAndroid/commits/test_id_select

Please tell me, if you want a pull-request.

**Comment by pardom-zz** [comment]
Oh, I see what you're saying. That's an interesting point, but I'm not 100% sure it should be doing more than you ask it to in the Select parameter. Maybe this is just a pitfall that I can document.

You can fix your code by selecting "Id, MockColumn".

``` java
new Select("Id, MockColumn").from(MockModel.class).where("MockColumn=?", 42).executeSingle();
```

Or don't pass anything in to get all columns.

``` java
new Select().from(MockModel.class).where("MockColumn=?", 42).executeSingle();
```

**Comment by vonloxley** [comment]
Should you change your mind, you can cherry-pick: vonloxley/ActiveAndroid@cf9ab36333be73359d6be6ce295bebbf2d84d78a which seems reasonably stable to me.
