### ISSUE TITLE
Register classes with ActiveAndroid instead of auto-discovery

### ISSUE THREAD

**Issue by qbproger** [pardom-zz/ActiveAndroid#162]
This is an enhancement.  It's mostly an idea, I'm wondering how it'd be received by the ActiveAndroid team before implementing it.  I was wondering what you think of registering classes with ActiveAndroid instead of auto-initialize.

This would mean that you wouldn't need any special code for tests (ie - the Robolectric fallback).

https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/ModelInfo.java#L135

What do you think?

**Comment by SeanPONeil** [comment]
I'm a fan of this. It's faster, more explicit, and easier to test.

**Comment by SeanPONeil** [comment]
You can actually already do this if you initialize ActiveAndroid with your own Configuration and add your model classes to it directly.
