### ISSUE TITLE
Chain multiple `where()` methods.

### ISSUE THREAD

**Issue by joshuapinter** [pardom-zz/ActiveAndroid#165]
Similar to Issue #126 except I would like to chain multiple `where()` methods so the following does not ignore the initial `where` condition: 

```
new Select().from(Inspection.class)
    .where("tag_uid = 153")
    .where("status = 'active'");
```

**Comment by test52test** [comment]
new Select().from(Inspection.class)
    .where("tag_uid = 153 AND status = 'active'");

**Comment by joshuapinter** [comment]
@test52test That works great if you're doing all your conditionals in one string. But in our setup we have a default conditional to exclude deleted items (`"deleted_at IS NULL"`) and then want to chain that with additional conditionals in other models and Activities.

Anyway, the Pull Request was merged so now it's possible to do this: 

```java
new Select().from(Inspection.class).where("tag_uid = 153").where("status = 'active'");
```

Much nicer.
