### ISSUE TITLE
Will ActiveAndroid support multiple databases in future?

### ISSUE THREAD

**Issue by hank-cp** [pardom-zz/ActiveAndroid#17]
Hey guys, thanks for your awesome work. 

I would like to know whether supporting multiple databases is in you roadmap? Our project requires to have multiple database and specify their name dynamically. It also requires to access these db at the same time. Now the implementation is quite "static" and hard to archive that goal.

**Comment by pardom-zz** [comment]
As of right now, this is not in the roadmap, however I understand the need to access two databases, as I have encountered this in the past. One possible suggestion is that you combine the two databases and prefix tables.

I haven't seen this feature in ORMs I've used in the past and it's an issue that's easy to overcome, so I didn't implement it.

If you would like to for the project and give implementation a try, I'd be happy to take a look.

**Comment by awong1900** [comment]
It is hard work, but no get a lot more.
