### ISSUE TITLE
Inner classes cause error

### ISSUE THREAD

**Issue by dublet** [pardom-zz/ActiveAndroid#186]
If trying to create a persisted inner class, to support a sort of PIMPL pattern, you get a run time exception.

Like so:
public class A {
    @Table(name="b")
    public class B extends Model {
        @Column(name="string")
         public String ;
         public B() {
         }
     }
}

It generates the exception upon runtime that the class doesn't contain a publically accessible constructor.

**Comment by SeanPONeil** [comment]
make B a public static class? I'm confused as to what you're trying to accomplish

**Comment by dublet** [comment]
Doh!
