### ISSUE TITLE
Cannot create database model

### ISSUE THREAD

**Issue by tomrozb** [pardom-zz/ActiveAndroid#194]
On 4.4.2 I get the error: 

```
                    `E  java.lang.RuntimeException: Unable to create application my.package.name: android.database.sqlite.SQLiteException: near ")": syntax error (code 1): , while compiling: CR
                       EATE TABLE IF NOT EXISTS Model ();
                    E   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4612)
                    E   at android.app.ActivityThread.access$1600(ActivityThread.java:169)
                    E   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
                    E   at android.os.Handler.dispatchMessage(Handler.java:102)
                    E   at android.os.Looper.loop(Looper.java:136)
                    E   at android.app.ActivityThread.main(ActivityThread.java:5476)
                    E   at java.lang.reflect.Method.invokeNative(Native Method)
                    E   at java.lang.reflect.Method.invoke(Method.java:515)
                    E   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                    E   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                    E   at dalvik.system.NativeStart.main(Native Method)
                    E  Caused by: android.database.sqlite.SQLiteException: near ")": syntax error (code 1): , while compiling: CREATE TABLE IF NOT EXISTS Model ();
                    E   at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                    E   at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1113)
                    E   at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:690)
                    E   at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                    E   at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                    E   at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                    E   at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1806)
                    E   at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1737)
                    E   at com.activeandroid.DatabaseHelper.executeCreate(DatabaseHelper.java:146)
                    E   at com.activeandroid.DatabaseHelper.onCreate(DatabaseHelper.java:66)
                    E   at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
                    E   at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                    E   at com.activeandroid.Cache.openDatabase(Cache.java:106)
                    E   at com.activeandroid.Cache.initialize(Cache.java:75)
                    E   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
                    E   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
                    E   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)
                    E   at my.package.name.MyClass.onCreate(MyClass.java:30)
                    E   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                    E   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4609)
                    E   ... 10 more`
```

**Comment by joshuapinter** [comment]
Is it only 4.4.2 that you get this error?

**Comment by tomrozb** [comment]
On Galaxy Nexus with 4.3 it works fine. I've just added the initialization to the Application class (as per documentation). I do not have any tables. It fails on two devices with 4.4.2.

**Comment by joshuapinter** [comment]
Good to know it’s isolated to 4.4.2. Thanks.

**Comment by tomrozb** [comment]
Have you reproduced this issue?

**Comment by joshuapinter** [comment]
Haven’t had a chance to, no.

**Comment by joshuapinter** [comment]
Hey @tomrozb, the test suite, including creating tables, works fine on 4.4.2. 

How have you setup your model(s)?

**Comment by tomrozb** [comment]
I've removed all the tables to nail down the problem. I don't have any tables at the moment. My application class looks like below. The exception occurs when the `ActiveAndroid.initialize(this)` is called.

`public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        ActiveAndroid.initialize(this);
    }   
    @Override
    public void onTerminate() {
        super.onTerminate();
        ActiveAndroid.dispose();
    }   
}`

Have you tested it on a emulator or a real device?

**Comment by joshuapinter** [comment]
The tests were run on an emulator.

If you extend `MyApplication` from `com.activeandroid.app.Application` instead of manually initializing it, does it still give the error? (And remove the `onCreate()` and `onTerminate()` overrides.)

You will also need to have `android:name="com.activeandroid.app.Application"` in your `<application>` declaration of your  `<manifest>` file. As per [Configuring Your Project](https://github.com/pardom/ActiveAndroid/wiki/Getting-started#wiki-configuring-your-project).

**Comment by tomrozb** [comment]
Yes the issue still occurs. `MyApplication` class extends the `com.activeandroid.app.Application` and the class's body is empty. The stack trace is the same as the one above.

**Comment by joshuapinter** [comment]
@tomrozb I tried recreating this error with a simple application running 4.4.2 and everything seems to work just fine so I think it has to do with your setup. I have uploaded this simple application for you to clone and try out. 

The repo is here: https://github.com/joshuapinter/ActiveAndroid_Test_Issue194

Try that and post back your result.

**Comment by tomrozb** [comment]
It turned out that this issue was probably caused by ROM bug. I've tested it on different device with 4.4.2 and it works just fine. Sorry for the troubles.

**Comment by joshuapinter** [comment]
No worries. Glad you nailed it down.

**Comment by developer--** [comment]
This bug steel occurs, tested on Nexus 7(Marshmallow), galaxy tab 10 (Lollipop)
