### ISSUE TITLE
no such column: Id

### ISSUE THREAD

**Issue by kevinmlong** [pardom-zz/ActiveAndroid#195]
I downloaded the that latest from Master and built it. All seemed fine until I tried tried to query the databse. After querying the db, I recieve the following:

android.database.sqlite.SQLiteException: no such column: Id: , while compiling: SELECT \* FROM OpsPeriods WHERE Id=? LIMIT 1

after exporting the DB I found that the the id column (Id) is not even in the table.

The .jar that's available here works just fine: https://github.com/thecodepath/android_guides/wiki/ActiveAndroid-Guide

Any thoughts?

**Comment by joshuapinter** [comment]
Can you post how you setup your models, @kmlong1183?

**Comment by kevinmlong** [comment]
Here is one of the models @joshuapinter:

```
import java.util.Date;
import com.activeandroid.Model;
import com.activeandroid.annotation.Column;
import com.activeandroid.annotation.Table;

@Table(name = "OpsPeriods")
public class OpsPeriod extends Model {


    @Column(name = "teamName")
    public String teamName;
    @Column(name = "memberName")
    public String memberName;
    @Column(name = "memberTitle")
    public String memberTitle;
    @Column(name = "unitName")
    public String unitName;
    @Column(name = "periodStart")
    public Date periodStart;
    @Column(name = "periodEnd")
    public Date periodEnd;

    public OpsPeriod() {

    }

}
```

**Comment by joshuapinter** [comment]
Great, thanks for posting that. I have a feeling it has to do with the default `Id` column not being set automatically.

I'm going to fix this, but for now you should be able to manually set the `Id` column in all of your tables by changing this:

```
@Table(name = "OpsPeriods")
```

To this:

```
@Table(name = "OpsPeriods", id = "_id")
```

Do that for each of your Models and let me know if that works.

_Just as a side note, the default `Id` column will be named `Id` for backwards compatibility, but I would recommend using `_id` as it plays nicely with what Android expects for `ListActivity`, `Cursor`, etc._

**Comment by joshuapinter** [comment]
Actually, scratch that. I see what your issue is. 

If you delete the public constructor method:

```
public OpsPeriod() {

}
```

It'll work fine.

Checkout the [Constructors](https://github.com/pardom/ActiveAndroid/wiki/Creating-your-database-model#wiki-constructors) section of the Wiki:

> ActiveAndroid uses the standard-constructor of your class to instantiate objects. If you define your own constructors you have to define a parameterless constructor as well.

**Comment by kevinmlong** [comment]
Ok. Thanks! Appreciate the help!

Perhaps the TheCodePath folks changed their code to make it work correctly?

**Comment by joshuapinter** [comment]
We recently made that change and they were linking to a previous version they had built. I updated their docs. 

Make sure to post back here with the outcome.

**Comment by kevinmlong** [comment]
No such luck. This is the exception:

android.database.sqlite.SQLiteException: no such column: _id: , while compiling: SELECT \* FROM OpsPeriods WHERE _id=? LIMIT 1

This is the model:

```

import java.util.Date;

import com.activeandroid.Model;
import com.activeandroid.annotation.Column;
import com.activeandroid.annotation.Table;

@Table(name = "OpsPeriods", id = "_id")
public class OpsPeriod extends Model {


    @Column(name = "teamName")
    public String teamName;
    @Column(name = "memberName")
    public String memberName;
    @Column(name = "memberTitle")
    public String memberTitle;
    @Column(name = "unitName")
    public String unitName;
    @Column(name = "periodStart")
    public Date periodStart;
    @Column(name = "periodEnd")
    public Date periodEnd;

}
```

**Comment by kevinmlong** [comment]
Ok. If I build using the project in the zip on the Getting Started page, it doesn't work. I cloned the project and built that and all is well. Not sure of the differences.

Thanks for the assistance @joshuapinter !

**Comment by joshuapinter** [comment]
That's really strange because the Getting Started link just zips the master branch and downloads it. They should be identical. In any case, glad it's working now.

**Comment by kevinmlong** [comment]
Well, thanks for the guidance. Much appreciated!

**Comment by joshuapinter** [comment]
:thumbsup:

**Comment by connect2learn** [comment]
Same here,
I encountered the same problem. I thought because database is not getting changed after I modified the class. Even i called ActiveAndroid.dispose(); This also went in vain because the same error popped up.
I created a new project and copied the same things..and ola...it worked ..NO idea what difference ..
