### ISSUE TITLE
Boolean Fields Aren't Returned Boolean Types

### ISSUE THREAD

**Issue by aejnsn** [pardom-zz/ActiveAndroid#203]
This works as intended:

``` java
return new Select()
            .from(Score.class)
            .where("valid = ?", 1)
            .execute();
```

This does not work as intended:

``` java
return new Select()
            .from(Score.class)
            .where("valid = ?", true)
            .execute();
```

My model looks like this:

``` java
public class Score extends Model
{
    @Column(name = "dateTime")
    public Date dateTime;

    @Column(name = "batteryLevel")
    public double batteryLevel;

    @Column(name = "value")
    public int value;

    @Column(name = "valid")
    public boolean valid;
}
```

If I had more time outside of the project I'm working on, I'd look into the code more and submit a PR to change this bit. Can someone confirm this is an issue or comment if I am missing something?

Thanks!

**Comment by joshuapinter** [comment]
Instead of doing `.execute()` can you do `.toSql()` and post the output here.

**Comment by aejnsn** [comment]
Alright. This is the returned string.

``` sql
SELECT * FROM Score WHERE valid = ?
```

**Comment by joshuapinter** [comment]
K, thanks. I'll take a look at this today.

In the meantime, best to use `0` and `1`.

**Comment by aejnsn** [comment]
Awesome thanks!

**Comment by joshuapinter** [comment]
@aejnsn This is fixed with the attached commits. Just waiting for @SeanPONeil to merge in the pull request.

**Comment by aejnsn** [comment]
Good work, sir. Thank you!
