### ISSUE TITLE
Could you upload generated jar file in zip

### ISSUE THREAD

**Issue by mbronzovic** [pardom-zz/ActiveAndroid#216]
I copy the zip content to my gradle 1.11 folder. I run gradle -q sourceJar and a build folder was generated with activeandroid-sources.jar file generated. But Eclipse dosent recognize com.activeandroid package or classes.
Could you upload the final jar file to use in eclise within the zip file like this activeandroid-x.y.z.jar format?
Thanx

**Comment by mbronzovic** [comment]
Damn, i already do it by running as an ANT build in Eclipse. Any way it could be nice to have the latest version of the jar already builded inside the zip file.
Thanks!

**Comment by markmooibroek** [comment]
For future reference. Build with Gradle is also available (and a breeze):
1. git clone
2. gradle build
3. Navigate to build/libs/activeandroid.jar
