### ISSUE TITLE
about the getting started doc

### ISSUE THREAD

**Issue by nhachicha** [pardom-zz/ActiveAndroid#223]
Hi,

why are you relying on onTerminate callback from your https://github.com/pardom/ActiveAndroid/wiki/Getting-started
this method is available only on emulated environment?

http://developer.android.com/reference/android/app/Application.html#onTerminate()

Cheers

**Comment by vonloxley** [comment]
Very good point!
This actually is the routine, where SQLiteDatabase.close() is called (via ActiveAndroid.Cache).

**Comment by no-1** [comment]
That's correct. I belive in production dispose calls should be called from the main activity's onPause or onStop method.

**Comment by BrainKu** [comment]
I think it's necessary for user to manual close it when the application has nothing to do with db.
if you call dispose() in onPause or onStop, you need to to call initialize again in onResume, or something would be wrong. Besides call initialize again would costs too much.

**Comment by vonloxley** [comment]
Uh, I somewhat forgot about this.

According to a [Google-Dev](https://groups.google.com/d/msg/android-developers/nopkaw4UZ9U/cPfPL3uW7nQJ) it shouldn’t be a problem to keep the connections open until the application is garbage-collected. Perhaps we should remove the `.dispose()`-call.

**Comment by BrainKu** [comment]
yes, I think it would confuse us since dispose in onTerminal() not really work. We just need to call initize when application is created.

**Comment by vonloxley** [comment]
I changed the documentation.
