### ISSUE TITLE
Using of distinct

### ISSUE THREAD

**Issue by Dwite** [pardom-zz/ActiveAndroid#225]
How to use distinct() on specific column or data from my model?
Select.distinct()  is not taking any arguments.

**Comment by ghost** [comment]
Just did that today and found an issue (-> #238).
You just do

``` java
Select("foo").distinct().from(Bar.class)
```

You would need to pull the patch (see pull request #239) from my fork to make that work.

Greetz,
Florian

**Comment by ellej16** [comment]
@flooberleitner thanks a lot :+1:
