### ISSUE TITLE
Migration - Does only the most recent migration file get exectued?

### ISSUE THREAD

**Issue by matthew-reilly** [pardom-zz/ActiveAndroid#240]
Say I upgrade from v1 to v5. Does only 5.sql get executed? Or 2, 3, 4, and 5?

**Comment by joshuapinter** [comment]
All of them up to the current version will get executed, if they exist.

**Comment by matthew-reilly** [comment]
Thx for quick response! Closing this.

**Comment by joshuapinter** [comment]
:thumbsup:

**Comment by ZackYahoo** [comment]
Hi Guys, I'm just wondering if there are tutorials on how activeAndroid is used for Database ans storable classes. Please send me a link if there is to both fore mentioned topics.

**Comment by ZackYahoo** [comment]
Hi Guys, I'm just wondering if there are tutorials on how activeAndroid is used for Database ans storable classes. Please send me a link if there is to both fore mentioned topics.
