### ISSUE TITLE
Unique Index Groups

### ISSUE THREAD

**Issue by rohanpatel2602** [pardom-zz/ActiveAndroid#250]
Is there a way to create unique index groups without having to do a raw SQL query to create the index?

**Comment by vonloxley** [comment]
@Column(name = "member1", uniqueGroups = {"group1"}, onUniqueConflicts = {ConflictAction.FAIL})

Should do the trick.

**Comment by rohanpatel2602** [comment]
@vonloxley Much appreciated!
