### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by kapso** [pardom-zz/ActiveAndroid#254]
I am a first time user of ActiveAndroid and had a few questions - 
- Is there a way to get first/last record?
- I have a `User` model which has only one record, is this the way to retrieve that one and only record - `new Select().from(User.class).executeSingle()`
- Does model generate its own id or can you provide a custom `id`. In my case I am retrieving JSON data from an API and saving that data on the phone using ActiveAndroid, but this data comes with its own `id` attribute, can I save my own id?

**Comment by pardom-zz** [comment]
``` java
// first or only record
new Select().from(Foo.class).executeSingle();

// last record
new Select().from(Foo.class).orderBy("_id DESC").executeSingle();
```

ActiveAndroid tells SQLite to generate a primary key called `_id`. You can store your `id` field using any non-keyword name other than `_id`.

**Comment by kapso** [comment]
Thanks a lot. So in case of `Item item = Item.load(Item.class, 1)` is it looked by `id` or `_id`?

Also looked up the code but coudnt find a reference to `_id`, I found this - https://github.com/pardom/ActiveAndroid/blob/df29214c9584d7b626f361e95b95daccb0c0114c/src/com/activeandroid/annotation/Table.java#L28

How is `Id` different from `id`? I have named my key column as `id` all lower case, is it going to conflict with `DEFAULT_ID_NAME`

**Comment by pardom-zz** [comment]
Column names are case-sensitive (I think?) so `Id` probably won't conflict with `id`, but you should verify that. The reason we have `Id` and `_id` is because AA originally used camel-case column naming for the primary key, but recently switched to use BaseColumns._ID.
