### ISSUE TITLE
Cascading save/delete?

### ISSUE THREAD

**Issue by blork** [pardom-zz/ActiveAndroid#26]
Perhaps it might be useful to have an annotation for relationships between models that determine whether they should be deleted or saved along with the parent object?

**Comment by vonloxley** [comment]
Having a look at the sources, I think setting @Column's onDelete to ForeignKeyAction.CASCADE should do the trick for deletes right know. At least from Frojo onwards.

**Comment by blork** [comment]
Thanks @vonloxley, I'll give that a go.

**Comment by vonloxley** [comment]
@blork: Please see #32!
