### ISSUE TITLE
methode getId in Model override

### ISSUE THREAD

**Issue by AX-NICOLAS** [pardom-zz/ActiveAndroid#263]
Hi, I have a problem when I use the library 'ActiveAndroid' including the model and to be more precise with the getId method. Each time, I get the error: 
Error: (22, 17) error: getId () in Member can not override getId () in Model 
overridden method is final. 

I want to use this model as well to parse my objects via retrofit for serialization in the database.

There would be no way around the problem? 

my class member : 

```
public class Member extends Model {

@Column(name = "id")
private int id;

@Column(name = "accessCode")
private String accessCode;

public void setId(int id){
this.id=id;
}

 public int getId(){
     return this.id;
}
```

}

Thank you

**Comment by ibrahimpenekli** [comment]
All Models have an id already. You should not declare it again.
You can access via getId() from Model class.

getId() returns null if Model created manually. (e.g. new ExampleModel())
getId() returns Model id if only if saved to database or fetched from database.

``` java
ExampleModel em = new ExampleModel()
em.getId() // Returns null

em.save();
em.getId() // Returns id that generated when saving database
```

If you want to set id manually, you can declare another Column with different name by id. Also you must set id manually all the time when you create model.

**Comment by SleeplessByte** [comment]
Additionally you might want to make it unique and replace on conflict:

```
@Table( id = BaseColumns._ID )
public SomeClass extends Model

   @Column( index = true, unique = true, onUniqueConflict = Column.ConflictAction.REPLACE )
   public String id;
```

**Comment by AX-NICOLAS** [comment]
For resolve my problem i have use @SerializedName("id")

import com.google.gson.annotations.SerializedName;
