### ISSUE TITLE
active android not saving correctly

### ISSUE THREAD

**Issue by tryadelion** [pardom-zz/ActiveAndroid#269]
hello, activeandroid i not saving correctly, the only error that could be related  is when installing the app:

09-09 23:37:41.072: E/SQLiteLog(9199): (10) Failed to do file read, got: 0, amt: 100, last Errno: 2
09-09 23:37:41.399: E/(9199): appName=//myappname//, acAppName=/system/bin/surfaceflinger
09-09 23:37:41.399: E/(9199): 0

there is no crash, but it won't simply save objects on the database.

**Comment by makunomark** [comment]
@tryadelion I'm stuck with the same issue. Did you solve it successfully? Thanks in advance.

(10) failed to do file read got 0 amt 4096 last errno 0

**Comment by tryadelion** [comment]
i fixed it by installing the latest build, cleaning the project and making sure the manifest had everything correctly setup.
