### ISSUE TITLE
Migrate to maven

### ISSUE THREAD

**Issue by danielgrosso** [pardom-zz/ActiveAndroid#27]
Michael, if you think its a good idea i can do it

**Comment by SeanPONeil** [comment]
+1 for this

**Comment by CharlesHarley** [comment]
+1 for this

**Comment by danielgrosso** [comment]
in my repo i have already migrated to maven...waiting for pardom to push

**Comment by uudashr** [comment]
+1 also

**Comment by SeanPONeil** [comment]
I don't see a pull request for this, should there be?

**Comment by danielgrosso** [comment]
Yes!!!, but i dont know how to create it!

**Comment by pardom-zz** [comment]
Sorry I've been AWOL for a bit - I'm a bit burnt out right now. Create a pull request and I'll have a look.

**Comment by achuinard** [comment]
Another +1 for this.

**Comment by ParAnton** [comment]
+1 for this

**Comment by SeanPONeil** [comment]
I'm going to work on this over the weekend and send a pull request your way @pardom

**Comment by a-thomas** [comment]
+1
Hi! I'm the developer of http://androidkickstartr.com/ . I'm waiting for this issue to be resolved before supporting your library on AndroidKickstartR (https://github.com/a-thomas/androidkickstartr/issues/60 ).

**Comment by mussa-ibragimov** [comment]
+1
Keep it plz!

**Comment by pardom-zz** [comment]
@danielgrosso or @SeanPONeil can you submit a pull request?

**Comment by luolong** [comment]
Why Maven, Gradle is going to be the new build system for Android, so I would suggest going with Gradle instead

**Comment by markmooibroek** [comment]
Looks like maven integration is coming soon =)
https://github.com/pardom/ActiveAndroid/pull/67

**Comment by pardom-zz** [comment]
Fixed in #67

Thanks @fmedlin!
