### ISSUE TITLE
How can I achieve such a delete

### ISSUE THREAD

**Issue by slidenerd** [pardom-zz/ActiveAndroid#271]
First of all, fantastic work on the library. I have been browsing the issues searching for cascade delete and stuff but I am not sure if it does this.
I have 2 tables like this Person and Score where each Person has a Score, I omitted the constructors and other irrelevant details to be precise.
//TABLE PERSON
@Table(name = "Person")
public class Person extends Model {

```
// Notice how we specified the name of our column here
@Column(name = "personName")
public String personName;

// Notice how we specified the name of our column here
@Column(name = "personAge")
public int personAge;

@Column(name = "personScore")
public Score personScore;
```

}

//TABLE SCORE
@Table(name = "Score")
public class Score extends Model {
    @Column(name = "scorePhysics")
    public int scorePhysics;
    @Column(name = "scoreChemistry")
    public int scoreChemistry;
    @Column(name = "scoreMaths")
    public int scoreMaths;
    @Column(name = "scoreBiology")
    public int scoreBiology;
}

If I delete a score row based on some criteria, it should also delete the corresponding Person row, and If I delete a Person row, it should also delete the corresponding score row. How can I achieve this. I read through the other issues where you were talking something about CASCADE but I am afraid I am not clear with this..Thanks for your reply in advance

**Comment by SleeplessByte** [comment]
You should have a look at the [SQL Lite documentation](http://www.sqlite.org/foreignkeys.html#fk_actions) because this is not the place for such a question.

**Comment by slidenerd** [comment]
Sorry mate, but this question is about how to delete using your library since the documentation has not specified anything about foreign key based deletes

**Comment by SleeplessByte** [comment]
On your foreign key column definition you add `onDelete = Column.ForeignKeyAction.CASCADE`. 

```
@Column(name = "personScore", onDelete = Column.ForeignKeyAction.CASCADE)
```

**Comment by slidenerd** [comment]
Thank you very much for your reply, just 1 question before I close this completely, can I see the list of all columns before I perform a delete so that I can selectively decide from my UI about deletion and as per the above mentioned table structure. which columns would ActiveAndroid create exactly inside its SQL queries other than my @Column annotated columns. Thanks in advance for your reply,

**Comment by SleeplessByte** [comment]
It only creates the primary ID column by default.

**Comment by slidenerd** [comment]
![snap 2014-09-13 at 13 09 49](https://cloud.githubusercontent.com/assets/5139030/4315564/d27641b8-3ef7-11e4-9e1a-af3fd2744af5.png)
So the tables created would be like this for the above structure using ActiveAndroid?

**Comment by SleeplessByte** [comment]
Exactly :+1: Except that the default id name is not `_id` but `id`.

**Comment by slidenerd** [comment]
Thank you very much for the precise answer, you can close the issue :D and once again, an awesome library, I have already written 3 articles on your library which s gonna be used by more than 60000 of my followers :D  Here s a link to the first one http://slidenerd.com/2014/09/10/tutorial-5-android-database-without-sqlite-code-using-activeandroid-library/ and there are 2 more. if you ever find, time, you can let me know if any changes need to be done to the articles. thanks in advance :D
