### ISSUE TITLE
How to JOIN multiple tables with conditions pertaining to columns from multiple tables?

### ISSUE THREAD

**Issue by slidenerd** [pardom-zz/ActiveAndroid#273]
![snap 2014-09-22 at 14 54 26](https://cloud.githubusercontent.com/assets/5139030/4354653/85c7a388-4240-11e4-8e55-9dd4deb4306e.png)
Thanks for the fantastic work so far. I would like to know how I can select a Person from Person table as per the above image where name=x and age =y and at the same time whose score in physics=z. How can I phrase this query using ActiveAndroid? Currently, I do this using 2 separate statements as follows
ArrayList<Person> people=new Select().from(Person.class).where("personName=? AND personAge=?", personName, personAge).execute();

ArrayList<Score> scores=new Select().from(Score.class).where("scoreChemistry=?", scoreChemistry).execute();

Now I am forced to manually check which of those foreign keys match with the Person ID like this in Java
boolean matchFound;
for(Person person: people){
matchFound=false;
for(Score score:scores){
if(person.personScore.getId()==score.getId()){
matchFound=true;
}

if(match is not found)
{
//remove that person object from the list.
}
}

Looking forward to your reply, thanks

**Comment by azzzy** [comment]
You can use a plain old SQL join. Something in the lines of:
`new Select().from(Person.class).join(Score.class).on(“persons.scoresId = scores._id”).where("personName = ? AND personAge = ? AND chemistryScore > ?“, personName, personAge, chemistryScore).execute();`

**Comment by SleeplessByte** [comment]
Use `.as( String name )` after the `.from( Class<? extends com.activeandroid.Model> class )` if you don't want to alias it.

**Comment by slidenerd** [comment]
Thanks :D for the replies :D
