### ISSUE TITLE
Parcelable in Model

### ISSUE THREAD

**Issue by ibabuk** [pardom-zz/ActiveAndroid#279]
I want to implement Parcelable in your class. Can I call super.writeToParcel(out, flags);?
My class looks like "class A extends Model implements Parcelable"

**Comment by r-gurzkowski** [comment]
Model does not implement parcelable, it is also impossible to write you own creator since you cannot set id externally (final private field). Good idea for feature.

**Comment by jmaffre** [comment]
We also have this requirement.
@archiecrown Why have you closed the issue ? 
Could you re-open ?

**Comment by tomblenz** [comment]
This would be a very helpful feature.

**Comment by aljibbs** [comment]
I liked the library until I wanted to pass the Model through intents. I just can't get Model ID and  i can't implement Parcelable. Please do something about it. Very cool library by the way.

**Comment by johnhiott** [comment]
we created a new class that inherits from Model and has a setAaId method that uses reflection to set the Id.  All of your models should inherit from the new class instead of Model.
now you can use the setAaId method in the constructor that takes the Parcel as an argument and use the getId() method in writeToParcel method. 

inheriting a project using ActiveAndroid has been a headache

**Comment by joshhornby** [comment]
This would be really nice to have.

@johnhiott Can you post a code example of your solution? Thanks

**Comment by johnhiott** [comment]
This is our model that extends AA's Model class

``` java
public class OpenModel extends Model {
    public void setAaId(Long id) {
        try {
            Field idField = Model.class.getDeclaredField("mId");
            idField.setAccessible(true);
            idField.set(this, id);
        } catch (Exception e) {
            throw new RuntimeException("Reflection failed to get the Active Android ID", e);
        }
    }
}
```

Now here is an example model using OpenModel:

``` java
@Table(name = "Sample")
public class Sample extends OpenModel implements Parcelable {

    @Column
    private String mName;

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(getId());
        dest.writeString(mName);
     }

    protected Site(Parcel in) {
        setAaId(in.readLong());
        mName = in.readString();
    }
}
```

@joshhornby

**Comment by billyriantono** [comment]
i have tried your solution @johnhiott still doesn't work :(

**Comment by BenoitDuffez** [comment]
It works through reflection but `setId()` would definitely be welcome.
Here's what I implemented, following @johnhiott's idea:

``` java
public abstract class ParcelableModel extends Model implements Parcelable {
    /**
     * Ensure the ID is set when creating from a parcel
     * Derived classes *must* call through super when overriding this constructor
     *
     * @param in Input parcel
     */
    public ParcelableModel(Parcel in) {
        setId(in);
    }

    /**
     * Empty constructor required by ActiveAndroid (when selecting data from SQLite)
     */
    public ParcelableModel() {
    }

    /**
     * Uses reflection to set the ID field from the parcel
     *
     * @param in Input parcel
     */
    private void setId(Parcel in) {
        try {
            Field idField = Model.class.getDeclaredField("mId");
            idField.setAccessible(true);
            idField.set(this, in.readLong());
        } catch (Exception e) {
            throw new RuntimeException("Reflection failed to get the Active Android ID", e);
        }
    }

    /**
     * Derived classes *must* call through super when overriding this method
     *
     * @param dest  The Parcel in which the object should be written.
     * @param flags Additional flags about how the object should be written.
     *              May be 0 or {@link #PARCELABLE_WRITE_RETURN_VALUE}.
     */
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(getId());
    }
}
```

**Comment by pesektomas** [comment]
@johnhiott thanks! Works for me fine.

**Comment by BenoitDuffez** [comment]
@archiecrown Does it mean we have to use reflection, and it will not be implemented?
