### ISSUE TITLE
OnSave callbacks

### ISSUE THREAD

**Issue by diedthreetimes** [pardom-zz/ActiveAndroid#292]
Currently there is now way to extend the saving mechanism.

For example, in my project I have a many-to-many relationship implemented as a join table. I would like the join table to be saved when either of the dependent objects is saved (so client code need not know of this table).

Overriding save would work, but it is final (for a decent reason). I could achieve the same functionality by using a callback. Either a void method onSave extendable by any inheriting class, or a callback list with registration methods. Any preference on which method is used? I'm happy to do the work.

**Comment by vonloxley** [comment]
You can Start with https://github.com/vonloxley/ActiveAndroid/commit/7dcb171ad85b98b4cb9c85503e4c7c507dd70ab5 if you like.

**Comment by diedthreetimes** [comment]
This looks great! Any reason this wasn't merged?

**Comment by vonloxley** [comment]
IIRC the discussions about this went nowhere. See #28 and #103.

**Comment by diedthreetimes** [comment]
Ah OK, well I'll just grab a version with you're commit.

Thanks for the heads up!

**Comment by hasnain-ahmad** [comment]
@diedthreetimes did you find & implement the solution, for showing error/log whether the record is saved or not?
