### ISSUE TITLE
ContentObservers

### ISSUE THREAD

**Issue by jesperborgstrup** [pardom-zz/ActiveAndroid#3]
This seems like a really great library!

How does your library work with ContentObservers? I'm thinking specifically about the CursorLoader pattern for populating ListViews with CursorAdapters?

**Comment by SeanPONeil** [comment]
He just pushed a ContentProvider wrapper for the internal SQLite database, so I believe if you package the current master branch into a jar, you can use a CursorLoader with a URI that has your package name as the authority.

**Comment by pardom-zz** [comment]
AA doesn't implement any observers for the content it returns, and there is no plan to do so. As SeanPONeil mentioned, I just pushed ContentProvider support, so if you absolutely needed it you could query from that, although it defeats the purpose of the library somewhat.
