### ISSUE TITLE
Documentation doubt

### ISSUE THREAD

**Issue by yaming116** [pardom-zz/ActiveAndroid#31]
[Getting started](https://github.com/pardom/ActiveAndroid/wiki/Getting-started)
Create your own, is not less realized

``` Java
       @Override
    public void onTerminate() {
        super.onTerminate();
        ActiveAndroid.dispose();
    }
```

**Comment by mikepenz** [comment]
The documentation also doesn't state how to get the ActiveAndroid.jar

The last version on the downlaod page is 2 months old (The download page is not linked on github anymore so you can't find it)

Perhaps a new section how to build or download the jar would be great?

**Comment by yaming116** [comment]
yes

**Comment by vonloxley** [comment]
Well, the wiki is editable by everyone…
