### ISSUE TITLE
Select query is failing.

### ISSUE THREAD

**Issue by aftabnaqvi** [pardom-zz/ActiveAndroid#319]
I created a table with following statement:

CREATE TABLE `DailyProgram` (
    `id`    INTEGER PRIMARY KEY AUTOINCREMENT,
    `day`   TEXT,
    `englishDate`   TEXT,
    `hijriDate` TEXT,
    `time`  TEXT,
    `program`   TEXT,
    `lastUpdated`   TEXT
);

Query:

```
public static List<DailyProgram> getAll() {
    return new Select().from(DailyProgram.class).execute();
}
```

I am getting following error:

12-23 12:01:39.486: E/CursorWindow(24210): Failed to read row 0, column -1 from a CursorWindow which has 57 rows, 7 columns.

queries on other two tables are working fine.

**Comment by jlhonora** [comment]
It seems that the primary key column should be named `Id` (note the uppercase i). See https://github.com/pardom/ActiveAndroid/issues/144

**Comment by aftabnaqvi** [comment]
@jlhonora Thank you! for catching the lower case "id". It did work.
