### ISSUE TITLE
CASCADE Action onDelete

### ISSUE THREAD

**Issue by iKiKi** [pardom-zz/ActiveAndroid#33]
Hi,

Lets take your example with Category and Item.

Category 
@Table(name = "Categories")
public class Category extends Model {

```
@Column(name = "Name", notNull = true, unique = true)
public String name;

public List<Item> items() {
    return getMany(Item.class, "Category");
}

public Category() {
    super();
}

public Category(String name) {
    super();
    this.name = name;
}

@Override
public String toString() {
    return new String("[" + Category.class.getName() + "] " 
            + "Name = " + name);
}
```

}

Item

@Table(name = "Items")
public class Item extends Model {

```
@Column(name = "Name", notNull = true, unique = true)
public String name;

@Column(name = "Category", onDelete = ForeignKeyAction.CASCADE)
public Category category;

public Item() {
    super();
}

public Item(String name, Category category) {
    super();
    this.name = name;
    this.category = category;
}

@Override
public String toString() {
    return new String("[" + Item.class.getName() + "] " 
            + "Name = " + name + " | "
            + "Category = " + category);
}
```

}

After saving one Category data with many items, when I delete the inserted Category, the items remain in database. Is the CASCADE Action upon onDelete is working ? How to establish properly ForeignKeyActions ?

Thanks.

**Comment by vonloxley** [comment]
Please see #32.

Could you merge https://github.com/vonloxley/ActiveAndroid/tree/reference_correct_table and try again?

**Comment by iKiKi** [comment]
I confirm DELETE ON CASCADE is now working with your https://github.com/pardom/ActiveAndroid/issues/32.

**Comment by vonloxley** [comment]
:tada:
