### ISSUE TITLE
hi,How can i store ArrayList to db?

### ISSUE THREAD

**Issue by macleo** [pardom-zz/ActiveAndroid#353]
hi pardom, 
thank you for provide this wonderful orm library.

problem:

public class Item extends Model {

```
         public ArrayList<Record> list;
```

}

How can i store ArrayList to db?

**Comment by ktomek** [comment]
Hi,

I think you have to create Record model class and make relation one to many between Item and Record.

**Comment by ivangag** [comment]
Hi,
as @ktomek says you have to create a Record model table and define in it a relationship with Item, for instance:

```
public class Record extends Model {

   // define relationship with Item Table.
    @Column(name = "Item")
    public Item mItem;

     public void setItem(Item item) {
        this.mItem = item;
    }
}

public class Item extens Model {
    // get all Record items relationed to current Item element
    public List<Record> getRecords() {
        return getMany(Record.class, "Item");

}

```

**Comment by macleo** [comment]
Very grateful for your help @ivangag  and @ktomek     ,I've learned it.

**Comment by ivangag** [comment]
@macleo you're welcome!

**Comment by macleo** [comment]
@ivangag ,if I want update a record already exist in db,What should I do?Thank You！

**Comment by macleo** [comment]
![Uploading AATransferNull.png . . .]()

**Comment by macleo** [comment]
Why mId  transfer by Bundle will be null?

**Comment by ivangag** [comment]
@macleo sorry what do you mean exactly? How did you build your class?

**Comment by macleo** [comment]
@ivangag ,thank you very much.
Perphaps Model havn't implements Serializable,cause can't transfer variable id in Activity.
pardon plz, I only know a little English.
