### ISSUE TITLE
and() does not work

### ISSUE THREAD

**Issue by code1997** [pardom-zz/ActiveAndroid#354]
new Select()
.from(Participant.class)
.where("Event = ?", event.getId())
.and("User = ?", user.getId()).executeSingle() returns null. 

My database is set up the way that this must allways return an item. I checked with an workarround (getting a list with where() and checking the condition of and() inside a for-loop). so the problem is either inside my syntax with the and, or inside active android.

**Comment by jlhonora** [comment]
What if you try with

```
new Select()
.from(Participant.class)
.where("Event = ? AND User = ?", event.getId(), user.getId())
.executeSingle()
```

That's pure SQL. If it still returns null then your entries do not match those conditions.

**Comment by code1997** [comment]
It returns Null, but my entries must be correct...
This is my workaround that does work:

User user = User.getUserByPhoneNumber(App.getPhoneNumber());
        List<Participant> participationOfUser = new Select()
                .from(Participant.class)
                .where("User = ?", user.getId()).execute();

```
    for (int idx = 0; idx < participationOfUser.size(); idx++)
    {
        if (event.getId().equals(participationOfUser.get(idx).getId()))
        {
            return participationOfUser.get(idx).getRank();
        }
    }
    return null;
```

I select i select the participations of the user and then select the specific participant of the event.
Participants is a table that resolves an m:n between Event and User

**Comment by jlhonora** [comment]
That code looks flawed, you're comparing `participant.id` with `event.id`. There will most probably be a match, specially in elements with low ids (1, 2, for example). You should be doing something like:

```
for (Participant p: participationOfUser) {
    if (event.getId().equals(p.event.getId())) {
        return p.getRank();
    }
}
return null;
```

**Comment by code1997** [comment]
You`re right. So the mistake should be at creating an Participant. At the moment a Participant is only created inside the constructor of an Event. so the mistake should be there, shouldnt it? But i cant see what should be wrong.

public Event(String name, String description, String type, boolean approachWanted,
                 boolean housingWanted, boolean logisticWanted, boolean agendaWanted)
    {
        this.name = name;
        this.description = description;
        this.type = type;
        this.approachWanted = approachWanted;
        this.housingWanted = housingWanted;
        this.logisticWanted = logisticWanted;
        this.agendaWanted = agendaWanted;

```
    Participant founder = new Participant(User.getUserByPhoneNumber(App.getPhoneNumber())
            , "founder", this);
    founder.save();
}
```

**Comment by jlhonora** [comment]
You need to save the event before creating the Participant relation.

**Comment by code1997** [comment]
And it works, thank you very much!
