### ISSUE TITLE
NPE when running Active Android in release build type with proguard enabled

### ISSUE THREAD

**Issue by vanniktech** [pardom-zz/ActiveAndroid#356]
When I run my application in release build type with proguard enabled I get the following NPE:

> java.lang.NullPointerException
>             at com.activeandroid.query.From.addArguments(From.java:160)
>             at com.activeandroid.query.From.where(From.java:100)

If I run the exact same code without proguard it works perfectly fine.

Since there is no real official proguard documentation for this library, I've searched on the internet and came across this one:

``` groovy
-keep class com.activeandroid.** { *; }
-keep class com.activeandroid.**.** { *; }
-keep class * extends com.activeandroid.Model
-keep class * extends com.activeandroid.serializer.TypeSerializer
-keepattributes Column
-keepattributes Table
-keepclasseswithmembers class * { @com.activeandroid.annotation.Column <fields>; }
```

Is there anything missing?

**Comment by arashmidos** [comment]
I have this exception using Proguard:

``` java
Impossible!: java.lang.NoSuchFieldException: mId
```

and when I turn proguard off, my app works fine. Any detail for Proguard configuration?

**Comment by jjerryyz** [comment]
@arashmidos Do you solve this problem now?

**Comment by jvagliat** [comment]
Same for me!

**Comment by vanniktech** [comment]
This one does work for me:

```
# ActiveAndroid
-keep class com.activeandroid.** { *; }
-keep class com.activeandroid.**.** { *; }
-keep class * extends com.activeandroid.Model
-keep class * extends com.activeandroid.serializer.TypeSerializer
```
