### ISSUE TITLE
Does ActivieAndroid support one model class to multiple tables?

### ISSUE THREAD

**Issue by Folyd** [pardom-zz/ActiveAndroid#362]
I have a model class named **Lesson**,meanwhile i have two table named **favorite_lessons** and **play_histories**,both tables are store Lesson object.But it seem to ActivieAndroid do not support one model to multiple tables? There are some solution to implement this? Any comment is welcome,thanks!:)

**Comment by ChristopheCVB** [comment]
You could add a field on your Lesson class that represent the type of lesson and store everything in the same table.
