### ISSUE TITLE
does not support  'like %%' when  using  where("item like '%?%'","sub")?

### ISSUE THREAD

**Issue by peiandsky** [pardom-zz/ActiveAndroid#368]

**Comment by jdzuri** [comment]
I tried using only "LIKE ?", without '%' chars, but it doesn't work.

Is there any way to make a simple SQL query?

**Comment by stroem** [comment]
One solution is that you can write: <query>.where("item LIKE ?", "%" + data + "%") to make sure it escaped correctly.

**Comment by cdaringe** [comment]
thanks @stroem  :)

**Comment by peiandsky** [comment]
where("item LIKE ?", "%" + data + "%")
