### ISSUE TITLE
TypeSerializer confused

### ISSUE THREAD

**Issue by ccfiel** [pardom-zz/ActiveAndroid#37]
Hello guys I am new in android so please bare with me :) Anyway, I just want to know more about TypeSerializer. I am confused how to used it. In the documentation It just show how Date Type Serializer was define but not how to used it. Does it mean if my model have a date property I need to used date type serializer? If yes how? If not. Then what is the used for serializer? If someone is kind enough to show some sample code. Thanks in advance.

**Comment by pardom-zz** [comment]
Type serializers are classes that handle the conversion of complex data structures into something that SQLite can actually use.

AA looks for both models and type serializers when it is initialized. Just by extending TypeSerializer, your serializer will be recognized and added.

You can see an example here:
https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/serializer/CalendarSerializer.java

**Comment by fcgregorio** [comment]
I think what he's asking for is a NOT how to extend TypeSerializer, rather, HOW do you use it in a model. The wiki definitely lacks this.

**Comment by hdavidzhu** [comment]
```
Just by extending TypeSerializer, your serializer will be recognized and added.
```

Thanks so much for writing this. I was so confused as to how ActiveAndroid was just automatically able to detect my serializer.
