### ISSUE TITLE
Bulk Insert

### ISSUE THREAD

**Issue by rex3du** [pardom-zz/ActiveAndroid#383]
I'm trying to save 43K objects into database. I have already used Bulk Insert  ActiveAndroid.beginTransaction(). However, it still take about 6 mins to save them. It takes 1 min in iOS App. Is there any solutions to suggestions?

Thank you

**Comment by jlhonora** [comment]
@rex3du Did you try using pure SQL queries? Something like:

```
for (int i = 0; i < N_ENTRIES; i++) {
    SQLiteUtils.execSql("INSERT INTO table_name (column1, column2) VALUES (value1, value2)");
}
```

Haven't tried that, though. Make sure to check this resources first:

https://www.sqlite.org/lang_insert.html
https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/util/SQLiteUtils.java

**Comment by rex3du** [comment]
@jlhonora Thank you for your help. Apparently, your solution solved the issue.
