### ISSUE TITLE
Can not use ActiveAndroid calling Model.save() always fail.

### ISSUE THREAD

**Issue by zzantares** [pardom-zz/ActiveAndroid#390]
Hello I want to use ActiveAndroid in my project, as far as I can see and read, my setup is correct but after 3 days of searching it seems to be imposible make it to work, I expose my problem here in a desperate manner.

What is the problem? Calling MyModel.save() always fail:

```
07-13 21:49:45.155  16328-16328/cf.antares.finalssh E/SQLiteLog﹕ (1) no such table: connections
07-13 21:49:45.165  16328-16328/cf.antares.finalssh E/SQLiteDatabase﹕ Error inserting port=22 hostname=some username=value Id=null password=secret
    android.database.sqlite.SQLiteException: no such table: connections (code 1): , while compiling: INSERT INTO connections(port,hostname,username,Id,password) VALUES (?,?,?,?,?)
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1467)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
            at com.activeandroid.Model.save(Model.java:153)
            .
            .
            .
```

**AndroidManifest.xml**

``` xml
<manifest
    .... >
    <application
        ..... >

        <!-- ActiveAndroid -->
        <meta-data android:name="AA_DB_NAME" android:value="finalssh.db" />
        <meta-data android:name="AA_DB_VERSION" android:value="1" />
        <meta-data android:name="AA_MODELS" android:value="cf.antares.finalssh.models.Connection" />

      <!-- rest of the file goes on -->
```

My model **Connection.java**:

``` java
package cf.antares.finalssh.cf.antares.finalssh.models;

import com.activeandroid.Model;
import com.activeandroid.annotation.Column;
import com.activeandroid.annotation.Table;
import com.activeandroid.query.Select;

import java.util.ArrayList;

/**
 * Model class to represent connections saved to the database.
 */
@Table(name = "connections")
public class Connection extends Model {
    @Column(name = "hostname")
    public String hostname;

    @Column(name = "username")
    public String username;

    @Column(name = "password")
    public String password;

    @Column(name = "port")
    public int port;

    public Connection() {
        super();
    }

    public Connection(String hostname, String username, String password, int port) {
        super();

        this.hostname = hostname;
        this.username = username;
        this.password = password;
        this.port = port;
    }

    public static ArrayList<Connection> all() {
        return new Select().all().from(Connection.class).execute();
    }
}
```

My Activity **MainActivity.java**

``` java
package cf.antares.finalssh;
import com.activeandroid.ActiveAndroid;
import cf.antares.finalssh.cf.antares.finalssh.models.Connection;

public class MainActivity extends ActionBarActivity {

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ActiveAndroid.initialize(this);
        setContentView(R.layout.activity_main);
    }
```

I have a button that fires a method to validate a form and save the connection model:

``` java
// After validation
Connection newConnection = new Connection(hostname, username, password, port);
newConnection.save();  // Exception thrown "E/SQLiteLog﹕ (1) no such table: connections"
```

I have read another similar problems, people recommends uninstalling the app and reinstalling, I have done that, clearing app data, even using `adb shell` to delete the created database, I've used my real device to test and also genymotion, changing the db name, the version and still the error is the same "no such table: connections".

Or perhaps do I need to create the table my self? (the wiki does not says anything about that).

I would appreciate any help. Thanks!

**Comment by jlhonora** [comment]
Why don't you subclass ActiveAndroid Application, in `YourApp.java`:

`YourApp extends com.activeandroid.app.Application`

?

Everything else seems fine. Calling `ActiveAndroid.initialize(this);` in your activity should be equivalent, but better try a "normal" setup before using a less known way.

**Comment by ZzAntares** [comment]
Hello thanks for the suggestion, but I can't do that since I'm already extending from `android.support.v7.app.ActionBarActivity`, if I extend `com.activeandroid.app.Application` a lot of errors appear from my menu implementation.

Is there any way to force a reset of some sort of cache from ActiveAndroid? o some obscure methods that may be helpful to call?

Thanks.

**Comment by zzantares** [comment]
Ok thanks for the suggestion, I've changed my AndroidManifest.xml:

``` xml
<manifest
    .... >
    <application
        android:name="com.activeandroid.app.Application"
        ..... >

        <!-- ActiveAndroid -->
        <meta-data android:name="AA_DB_NAME" android:value="finalssh.db" />
        <meta-data android:name="AA_DB_VERSION" android:value="1" />
        <meta-data android:name="AA_MODELS" android:value="cf.antares.finalssh.models.Connection" />

      <!-- rest of the file goes on -->
```

And commented out the `ActiveAndroid.initialize(this);` on my MainActivity.java

But the error is still the same:

```
07-14 16:58:42.140    5812-5812/cf.antares.finalssh E/SQLiteLog﹕ (1) no such table: connections
07-14 16:58:42.144    5812-5812/cf.antares.finalssh E/SQLiteDatabase﹕ Error inserting port=54322 hostname=una username=dos Id=null password=tres
    android.database.sqlite.SQLiteException: no such table: connections (code 1): , while compiling: INSERT INTO connections(port,hostname,username,Id,password) VALUES (?,?,?,?,?)
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1467)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
            at com.activeandroid.Model.save(Model.java:153)
            at cf.antares.finalssh.NewConnectionActivity.saveConnection(NewConnectionActivity.java:73)
```

**Comment by jlhonora** [comment]
That change won't work. If you can't make your app inherit from `activeandroid.application` then do this:

```
public class MyApplication extends YourBaseApplication {
    @Override
    public void onCreate() {
        super.onCreate();
        ActiveAndroid.initialize(this);
    }
}
```

**Comment by zzantares** [comment]
Thanks @jlhonora I've already tried that is in my initial message, is there any other obscure methods that could help to force the table creation?

Thanks.

**Comment by jlhonora** [comment]
No, notice the difference: My proposed code is for `Application`. In your initial code you're initializing ActiveAndroid in `Activity`.

**Comment by zzantares** [comment]
Ok, thanks, I've tried your code but this error is shown:

```
Error:(8, 14) error: no suitable method found for onCreate()
method ActionBarActivity.onCreate(Bundle) is not applicable
(actual and formal argument lists differ in length)
method FragmentActivity.onCreate(Bundle) is not applicable
(actual and formal argument lists differ in length)
method Activity.onCreate(Bundle,PersistableBundle) is not applicable
(actual and formal argument lists differ in length)
method Activity.onCreate(Bundle) is not applicable
(actual and formal argument lists differ in length)
```

**Comment by encastellano** [comment]
What version of android are you running? lollipop? In lollipop exist a problem with sqlite. I updated de ActiveAndroid to one Fork https://github.com/dreipol/ActiveAndroid

In this fork many bugs are fixed. I hope this work for you.

**Comment by scascacha** [comment]
@encastellano how did you updated to that fork? I'm using Gradle

**Comment by encastellano** [comment]
@scascacha download the source code and import in your project, not gradle version for this repository.

**Comment by phoenix26** [comment]
I'm sure this guy bored to try ActiveAndroid.Cause im getting same error "No such table".i tried initilaze app, changed "AA_DB_VERSION" value to "2 and more", tried on emulator and real device (via fresh install-reinstall).But same error happens.I'm using ActiveAndroid-3 and Android 24 api on my project. 
p.s best solution is "just remove ActiveAndroid from ur project completetly".thank you.

**Comment by scascacha** [comment]
This works for me every time (yes, quite awful but works), just implement this on your `AndroidManifest.xml`

`<meta-data
            android:name="AA_MODELS"
            android:value="com.example.Table1,com.example.Table2"/>`

Be sure to list ALL your tables and works just nice.

**Comment by zzantares** [comment]
Just for the record... In the end I didn't make it work, so I just used Sugar ORM instead.

**Comment by Dona278** [comment]
I'm sure that it's too late but i write this comment for other people that read this issue.
In the Connection.java file the package is ```package cf.antares.finalssh.cf.antares.finalssh.models;``` and i think is wrong and in the manifest the model is searched for ```cf.antares.finalssh.models.Connection```.

**Comment by chenycu** [comment]
I found the reason for the error.
`<meta-data android:name="AA_DB_NAME" android:value="finalssh.db" />`
change into
`<meta-data android:name="AA_DB_NAME" android:value="finalssh" />`

**Comment by zzantares** [comment]
4 years latter 😆 I don't even remember were that codebase is but thanks 👍
