### ISSUE TITLE
'IN' clause

### ISSUE THREAD

**Issue by rex3du** [pardom-zz/ActiveAndroid#392]
Anyone know how to do 'IN' clause ??

My code is:
 String query = "('Free Loaders','VIP')";
 List<Attendee> searchResults = new Select().from(Attendee.class)
                .where("ticket_type in ?",query).execute();

This one does not work. How to implement IN clase ??

**Comment by jlhonora** [comment]
This should give you an idea on how to make it work:

```
    public void testInQuery() {
        Waypoint w = new Waypoint();
        w.save();

        Waypoint w2 = new Waypoint();
        w2.save();

        Long[] ids = {w.getId(), w2.getId()};

        Character[] placeholdersArray = new Character[ids.length];
        for (int i = 0; i < ids.length; i++) {
            placeholdersArray[i] = '?';
        }

        String placeholders = TextUtils.join(",", placeholdersArray);

        List<Waypoint> waypoints = new Select()
                .from(Waypoint.class)
                .where("Id IN (" + placeholders +")", ids)
                .execute();

        assertEquals(2, waypoints.size());
    }
```

It seems that the arguments cannot be an array of primitives, but that's not your case.

**Comment by rex3du** [comment]
@jlhonora Thank you for your help. 
you are right. It works with using Id instead of string
