### ISSUE TITLE
Have one use it in android M, can write but not read

### ISSUE THREAD

**Issue by tidezyc** [pardom-zz/ActiveAndroid#397]
I can write data to sqlite, but when query, it return zero result

**Comment by stroem** [comment]
Make sure your Application extends com.activeandroid.app.Application (if you use custom application), and that your model extends Model. And also that the model have a empty constructor which call its superclass.

**Comment by tidezyc** [comment]
@stroem it run well on pre M, so it will not be this problem

**Comment by HolgerWirth** [comment]
I have the same problem on a device with Marshmallow. The same code runs flawlessly on Lollipop devices but on Marshmallow querying the database does not work. No error, just no data.

During init of ActiveAndroid I get the following warning:
com.holger.mptest W/System: ClassLoader referenced unknown path: /data/app/com.holger.mptest-2/lib/arm

My AA_DB_VERSION is 2 and the domain is com.holger.mptest

Thank you for your support!

Regards,
Holger

**Comment by tidezyc** [comment]
@HolgerWirth I had fix my problem, it caused because I make the Model with private access

**Comment by HolgerWirth** [comment]
Yes, it works! Thank you very much for your help.
I made my Model class 'public'. This solved the problem.

I still don't know why it was working on < API 23 devices. Very strange...

**Comment by tidezyc** [comment]
@HolgerWirth it seem like a bug of android java sdk, which ignore check accessible of the Constructor and android M had fix this.

**Comment by dazza5000** [comment]
@tidezyc thank you so much! I had this issue and solved it by making the Model class public!

**Comment by tidezyc** [comment]
http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime
