### ISSUE TITLE
onUniqueConflict does not work

### ISSUE THREAD

**Issue by yoavi2** [pardom-zz/ActiveAndroid#399]
Hi,
I am trying to use the onUniqueConflict = Column.ConflictAction.REPLACE on one of my fields (ObjectId).
The table seems to be created correctly:
CREATE TABLE Location (_id INTEGER PRIMARY KEY AUTOINCREMENT, locationName TEXT NOT NULL ON CONFLICT FAIL, locationX REAL NOT NULL ON CONFLICT FAIL, locationY REAL NOT NULL ON CONFLICT FAIL, ObjectId TEXT NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT REPLACE)
The behavior i'm expecting is when an object is saved the second time (without an _id - mId), it should be replaced by the new one and have the same _id returned from INSERT statement.
Instead I am getting the following error:
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
and the object is not saved.
Your help will be much appreciated

Edit:
The problem seems to be due to nested object. replace deletes the existing row and gives the new row a new _id, causing father object to lose it's relationship to the object.

**Comment by evanradcliffe** [comment]
How did you fix this issue?
