### ISSUE TITLE
Multi-Statement Migration

### ISSUE THREAD

**Issue by abegosum** [pardom-zz/ActiveAndroid#403]
I'm trying to make multiple changes in a single migration script and am only seeing the first statement run on update.  For example, I have a migration file 3.sql with the following:

```
ALTER TABLE Items ADD COLUMN Count INTEGER;
ALTER TABLE Items ADD COLUMN InStock INTEGER;
```

And I've added the columns to the table as such:

```
@Column(name = "Count")
public Integer count;

@Column(name = "InStock")
public boolean inStock;
```

If I increment the `AA_DB_VERSION` to 3 and install over a previous installation then pull down the tables, only the `Count` column is created, indicating that only the first statement of my script is being executed.  If I uninstall and reinstall, both columns appear in the table as expected because it creates from the model.

Is this a limitation of SQLite?  Not sure why only a portion of my script is firing.

**Comment by jlhonora** [comment]
Please check https://github.com/pardom/ActiveAndroid/issues/402

**Comment by abegosum** [comment]
Thanks- missed that one in my search.
