### ISSUE TITLE
Working with an existing db (coming from iOS)

### ISSUE THREAD

**Issue by fvisticot** [pardom-zz/ActiveAndroid#41]
I have a working iOS application storing data in a myapp.sqlite file.
I would like to reuse this myapp.sqlite directly with the ActiveAndroid stack.
- How to do that ? 
- Is it possible ?

**Comment by xArthasx** [comment]
It's possible if you keep the structure and use migrations... (if u have the sqlite name the db in the manifest equals to the file and put the file in the assets directory)

**Comment by fvisticot** [comment]
Tx for your Quick answer !!
Can you please detail what you mean by migration...?
My objective is to use the SQLite file as it is and create my model (java class) regarding sqlite tables.
So for me no migration is required ...

Fred
Envoyé de mon iPhone

**Comment by xArthasx** [comment]
If you have the file (sqlite database) and the tables keep the same structure as the class you made in java, you should be able use the database by coping the file (sqlite database) to the assets directory (project directory) and set the AA_DB_NAME equals to the name of the file.

**Comment by fvisticot** [comment]
Hello,
I have created a simple project with a very simple db but it does not
work...
What I have done
1. I have created a basic SQLite DB with 1 table and 2 fields (text)
2. I have placed this sqlite file in the assets directory
3. I have created the model from the table
4. I have created the Application class
5. I have modified the manifest file
6. I have try to make a call to list all db objects..

My pb:
- No object returned :(

I'm not sure the db file is read and I do not see any trace or error from
the active android stack...

Can you please help me to understand where is the issue ?

My sample project is attached to the mail

Regards,

Fred

**Comment by xArthasx** [comment]
Github.com ignores any attachement from emails. my email is alvaro.ardila@gmail.com

**Comment by xArthasx** [comment]
I just imported your code and it's actually failing because of a bug in Version 3.0, download the latest source code and make the jar.

it should be working now

**Comment by xArthasx** [comment]
By the way after you update the library delete the app from your phone and then reinstall it (or change the version of the database in the manifest).

**Comment by fvisticot** [comment]
It works fine using the code from github !!! Tx a lot for your quick
support...

Fred

**Comment by xArthasx** [comment]
Close this issue :+1:
