### ISSUE TITLE
How to setup project for ANT build

### ISSUE THREAD

**Issue by josh-burton** [pardom-zz/ActiveAndroid#42]
Hey guys,

I'm trying to build my android app using Ant, but it keeps giving me an error saying that the activeandroid package does not exist.

I'm not using the activeandroid jar, but instead I have checked out the project from github and referenced that project into my android app project.

Whats the correct way to do this? I would prefer to not put a jar in the android apps libs folder, because its much easier to update the library from github.

Thanks

**Comment by vonloxley** [comment]
It works for me:  https://github.com/vonloxley/ActiveAndroid. But I turned it into an android-project.

**Comment by josh-burton** [comment]
How did you turn it into an android project?

**Comment by vonloxley** [comment]
vonloxley/ActiveAndroid@28a037a576e479bff82b15caad32ca3501ede17e and vonloxley/ActiveAndroid@d87893a95ae3b2d98106ab72b587d9846c063960

**Comment by josh-burton** [comment]
Thanks, I've ended up just using your branch. Out of interest whats the difference between your branch and the trunk?

**Comment by vonloxley** [comment]
I incorporated a lot of features me and other people wrote for AA. It also contains _lots_ of bug-fixes that don’t appear in trunk.
My branch is an android-project, contains an AsyncTaskLoader (by Sam Oakley), fixes transaction-handling, adds some callbacks (wip), fixes foreign-key references for cascading updates and deletes, fixes a bug in Set, and and and…
