### ISSUE TITLE
How to backup and restore a db file

### ISSUE THREAD

**Issue by nologinatgit** [pardom-zz/ActiveAndroid#421]
I have to backup my data from my application and on reinstall, I have to restore it.

Does AA support it?
If yes, how could I do it?

**Comment by Pozzoooo** [comment]
Database is saved on default Android folder, you can set its name by setting 
<meta-data
            android:name="AA_DB_NAME"
            android:value="yourdatbasename.db" />

Here is the reference doc: https://github.com/pardom/ActiveAndroid/wiki/Getting-started#configuring-your-project

With this defined you can backup as you prefered.

ps: you may backup even with the default name (not setting AA_DB_NAME).

**Comment by nologinatgit** [comment]
I know I can probably save the db file from the file system, but that is not AA-related, I could do it with any file. The point is if AA supports any built in method for saving and restoring its own database.

**Comment by Pozzoooo** [comment]
What I meant is that you can use any database backup system as it is just a normal Sqlite database file.
On ActiveAndroid side there is no backup system built-in.

**Comment by nologinatgit** [comment]
Maybe you should consider to create a built-in solution, it would be a nice feature :)

**Comment by Pozzoooo** [comment]
In my mind it is not a fit to ActiveAndroid.
But anyway I'm just an ActiveAndroid user like you are, and ActiveAndroid is open source, so feel free to build your own solution and contribute with ActiveAndroid if it sounds the best approach to you.

**Comment by hasnain-ahmad** [comment]
@pardom-zz Please add back/restore functionality in the library. It will be very helpful. Also, it is humble request to maintain and upgrade the library.
