### ISSUE TITLE
Many to many relationship

### ISSUE THREAD

**Issue by Efor18** [pardom-zz/ActiveAndroid#46]
Hi,

How could I create a many to many relationship?

**Comment by josh-burton** [comment]
I'm also wondering how to do this.

**Comment by vonloxley** [comment]
Did you try:

``` java
public class Foo extends Model {
[…]
}
public class Bar extends Model {
[…]
}

public class FooBar extends Model {
    @Column(name = "foo", onDelete=ForeignKeyAction.CASCADE)
    public Foo foo;
    @Column(name = "bar" onDelete=ForeignKeyAction.CASCADE)
    public Bar bar;

    public List<Foo> foos() {
        return getMany(Foo.class, "FooBar");
    }
    public List<Bar> bars() {
        return getMany(Bar.class, "FooBar");
    }
}
```

This will need my branch: https://github.com/vonloxley/ActiveAndroid, because of #32 and is completely untested.

You need to define a unique index on FooBar(foo, bar) as well, which isn’t possible with AA right now.

HTH

**Comment by Efor18** [comment]
Thanks, finally I did it that way.

**Comment by pardom-zz** [comment]
@vonloxley has it right. This is common db architecture for many-to-many relationships. Rails ActiveRecord handles it a bit differently, whereas this is a bit more transparent.

**Comment by alexvbush** [comment]
So this is the way to do many-to-many with ActiveAndroid, through a join Model/Table?

**Comment by hayksaakian** [comment]
would be nice if there was some analogue to has_and_belongs_to_many

**Comment by SwampMobile** [comment]
How does one define a "unique index on FooBar" as mentioned above?

**Comment by waclock** [comment]
Could you give us a more detailed example? I still can't manage to get a many-to-many relationship working. Do I have to explicitly create the "FooBars" when creating a Foo/Bar ?

**Comment by prilaga** [comment]
Here is my answer on another place: http://stackoverflow.com/questions/26207948/activeandroid-many-to-many-relationship/39203783#39203783
