### ISSUE TITLE
AA weird behavior with Instant Run on Android Studio 2.0

### ISSUE THREAD

**Issue by rohanraarora** [pardom-zz/ActiveAndroid#468]
So like many other developers I shifted to Android Studio 2.0 and suddenly my app started crashing due to the NullPointerException on getTableName().
To resolve this problem I found two solutions
1. Turn Instant Run off
2. Specify Model names in Manifest file which is explained in the wiki in [speeding up application startup](https://github.com/pardom/ActiveAndroid/wiki/Creating-your-database-model#speeding-up-application-startup).

Turning instant runs resolves the issue but I really wanted to use it as my laptop is too slow :(
So the second options seems good for me also it should speed up my application startup, right?

But when I did this my app showed a weird behaviou.
The startup time slowed instead of increasing when it runs for the first time after than it works smothly. It really slows down a lot.
Also my app size reduced to ~5Mb from ~19Mb and Data size increased from ~1Mb to ~7Mb

Can anyone explain why it is happening? and can't we do something to prevent it?

**Comment by PtiPingouin** [comment]
I personally add my models programmatically with:

`ActiveAndroid.initialize(Configuration.Builder(myContext).setModelClasses(myModels).create());`

This will fix 100% of your problems.
