### ISSUE TITLE
Pre-populated databases?

### ISSUE THREAD

**Issue by powerje** [pardom-zz/ActiveAndroid#48]
I see this link: 
http://github.com/pardom/ActiveAndroid/wiki/Pre-populated-databases

and notice it says coming soon. Is this functionality built, but just not documented there yet? In:
https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/DatabaseHelper.java

there is a method for copying a pre-populated database, I'm just not sure of the proper way to do it. Any pointers?

**Comment by powerje** [comment]
When I modified my database I had changed the primary keys to _id initially, but after messing with AA a bit it looks like it is expecting Id for the primary key. It seems the copying is handled already, I just didn't use the correct primary key.

**Comment by vonloxley** [comment]
Would you like to write a sentence or two about prepopulated dbs in the wiki?

**Comment by powerje** [comment]
Sure, just be sure to correct me if I got anything wrong :)

**Comment by tagrudev** [comment]
Can you be more specific on how to do it I have renamed my _id to Id columns, but it doesn't seem to copy the database into the /data/data... folder automatically. I tried calling an  instance of https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/DatabaseHelper.java (this way the db  seems to get copied in the /data folder ) but I can't seem to get it working with the models

**Comment by tristanoneil** [comment]
I've also been unable to get this working. Just doesn't seem to copy over.

**Comment by matteinn** [comment]
I have the same problem :(

**Comment by dnlbauer** [comment]
same here :(
maybe its an option to copy the .db file manually? (havent test it yet)

**Comment by joshuapinter** [comment]
Has anyone had any success with this?

**Comment by joshuapinter** [comment]
Nevermind. I figured it out. I also updated the wiki on this to help others: 

https://github.com/pardom/ActiveAndroid/wiki/Pre-populated-databases

**Comment by robpearlman** [comment]
Another note for people who end up on this page - 
Make sure you are using 3.1.0 not 3.0.0
changing the id default field name (ie -  @Table(name = "Items", id = "_id") had no effect for me, and in fact broke my app when I was trying to retrieve objects by primary key/id (which was still being described as Id in the copied database)

**Comment by KhalidElSayed** [comment]
My DB inside assets folder and I'm using latest version of AA library (3.1.0) and still no success.
So I need working example about using pre-populated database (which is already set in assets) with AA.

**Comment by joshuapinter** [comment]
Have you tried looking at https://github.com/pardom/ActiveAndroid/wiki/Pre-populated-databases?
