### ISSUE TITLE
is there an async save?

### ISSUE THREAD

**Issue by danieltigse** [pardom-zz/ActiveAndroid#494]

**Comment by PtiPingouin** [comment]
No.

**Comment by hasnain-ahmad** [comment]
@danieltigse @pardom-zz  @PtiPingouin  What will be the solution to it?

**Comment by hasnain-ahmad** [comment]
> @danieltigse @pardom-zz @PtiPingouin What will be the solution to it?

still waiting for it....

**Comment by naXa777** [comment]
@hasnain-ahmad 

1. Why do you ask your question on a **Closed** Issue?

    This issue (and your question) is already answered: There's NO async save in ActiveAndroid. Why do you keep asking? In future, note that you have better chances to receive an answer if you open a new issue or ask your question on StackOverflow. Please do your researh to find if your question was previously asked.

2. Why do you upvote your own comment? It looks silly and desperate.

3. ActiveAndroid library is deprecated. Consider migration to ReActiveAndroid.

    ReActiveAndroid has `saveAsync` method - https://github.com/ImangazalievM/ReActiveAndroid/issues/5

**Comment by hasnain-ahmad** [comment]
@naXa777 We have already use ActiveAndroid library in the project, that is live and used by our thousand of users. How can we move to another ORM, maybe they lose their data because the app is running in offline mode?

We already have put the question on the StackOverflow but still no answer. 
https://stackoverflow.com/questions/52635912/implementing-multiple-sqlite-orm-libraries-in-a-single-android-project

**Comment by hasnain-ahmad** [comment]
> @naXa777 @pardom-zz  We have already use ActiveAndroid library in the project, that is live and used by our thousand of users. How can we move to another ORM, maybe they lose their data because the app is running in offline mode?
> 
> We already have put the question on the StackOverflow but still no answer.
> https://stackoverflow.com/questions/52635912/implementing-multiple-sqlite-orm-libraries-in-a-single-android-project

@naXa777 Still waiting for your response. I have already post question on different forums are following.

1. https://github.com/amitshekhariitbhu/Fast-Android-Networking/issues/458
2. https://stackoverflow.com/questions/58688412/memory-allocation-ui-stucks-hangs-while-network-call-rx2androidnetworking
3. https://github.com/ImangazalievM/ReActiveAndroid/issues/69
