### ISSUE TITLE
Caching Model objects eats up memory and is hard to track down.

### ISSUE THREAD

**Issue by veelck** [pardom-zz/ActiveAndroid#51]
Hi,

First of all - thanks for great DB library :)

The problem we had is: we're using ActiveAndroid to store all the data we fetch from remote server. Mostly it's information about albums of images, so quite a lot String information (image urls, album details etc.). Thing is, we query DB a lot to get always up-to-date information, but we noticed, that each Select generates around 2-3KB memory overhead, that is later on not really used.

When tracking down the problem, I noticed, that Select is calling `SQLiteUtil.processCursor` method behind the scenes, which is calling

```
                    // TODO: Investigate entity cache leak
                    T entity = (T) entityConstructor.newInstance();
```

The leak mentioned in comment might not exactly be the leak but bloat, since `Model` in it's constructor is doing:

```
Cache.addEntity(this);
```

Anyway, thing is - clearing the cache with `ActiveAndroid.clearCache()` allows to free the 'lost' memory.

Please consider using LruCache instead of HashSet, as it will allow to specify how much memory you are willing to give away for DB cache to work.
Otherwise it will be hard to maintain the HashSet.

As an interesting point - this Set is able to grow up to several MB on device, which is, at least for me, killing possibility to load bitmap - that was the main issue I started to track it down and decided to write an issue report. Maybe someone else is also looking for answers and hits this post :-)

Keep up great work.

Cheers,
Damian

**Comment by vonloxley** [comment]
Hi Damian!

Thanks for the writeup. Would you like to have a look at vonloxley/activeandroid@6d78a8219be7789c3bcfd985cea39997c159ab7c? It’s based on pardom’s master and should apply cleanly.

**Comment by veelck** [comment]
@vonloxley thanks, I will for sure try it out :)

**Comment by pardom-zz** [comment]
After digging through the code to find some caching errors of my own, I realized that at some point caching had been de-implemented. Check the latest to see if your issue is fixed.
