### ISSUE TITLE
How to query all data in table

### ISSUE THREAD

**Issue by daothanhha** [pardom-zz/ActiveAndroid#521]
how to write this query 
  public static List<MyLearningOffline> getAllDataMyLearning() {
        return new Select()
                .from(MyLearningOffline.class)
                .execute();
    }
this code not working 
SELECT *FROM MyLearningOffline
please help me

**Comment by uncledoc** [comment]
MyLearningOffline is not defined, maybe.
what errors in the logcat?

**Comment by daothanhha** [comment]
this is
@Table(name = "MyLearningOffline")
public class MyLearningOffline extends Model {
    @Column(name = "cat_name")
    public String cat_name;
    @Column(name = "cat_description")
    public String cat_description;
    @Column(name = "sortorder")
    public String sortorder;
    @Column(name = "fullname")
    public String fullname;
    @Column(name = "shortname")
    public String shortname;
    @Column(name = "idnumber")
    public String idnumber;
    @Column(name = "summary")
    public String summary;
    @Column(name = "filepath")
    public String filepath;
    @Column(name = "filename")
    public String filename;
    @Column(name = "coursetype")
    public String coursetype;
    @Column(name = "course_group")
    public Integer course_group;
    @Column(name = "remoteid")
    public Integer remoteid;
    @Column(name = "cat_id")
    public Integer cat_id;
    @Column(name = "startdate")
    public Integer startdate;
    @Column(name = "created")
    public Integer created;
    @Column(name = "modified")
    public Integer modified;
    @Column(name = "last_access")
    public Integer last_access;
    @Column(name = "enrol_time")
    public Integer enrol_time;
    @Column(name = "timeend")
    public Integer timeend;
    @Column(name = "time_completed")
    public Integer time_completed;
    @Column(name = "self_enrolment")
    public Integer self_enrolment;
    @Column(name = "enroled")
    public Integer enroled;
    @Column(name = "guest")
    public Integer guest;
    @Column(name = "completion_status")
    public Integer completion_status;

    public MyLearningOffline() {
        super();
    }

    public MyLearningOffline(String cat_name, String cat_description, String sortorder, String fullname, String shortname, String idnumber, String summary, String filepath, String filename, String coursetype, Integer course_group, Integer remoteid, Integer cat_id, Integer startdate, Integer created, Integer modified, Integer last_access, Integer enrol_time, Integer timeend, Integer time_completed, Integer self_enrolment, Integer enroled, Integer guest, Integer completion_status) {
        this.cat_name = cat_name;
        this.cat_description = cat_description;
        this.sortorder = sortorder;
        this.fullname = fullname;
        this.shortname = shortname;
        this.idnumber = idnumber;
        this.summary = summary;
        this.filepath = filepath;
        this.filename = filename;
        this.coursetype = coursetype;
        this.course_group = course_group;
        this.remoteid = remoteid;
        this.cat_id = cat_id;
        this.startdate = startdate;
        this.created = created;
        this.modified = modified;
        this.last_access = last_access;
        this.enrol_time = enrol_time;
        this.timeend = timeend;
        this.time_completed = time_completed;
        this.self_enrolment = self_enrolment;
        this.enroled = enroled;
        this.guest = guest;
        this.completion_status = completion_status;
    }

    public String getCat_name() {
        return cat_name;
    }

    public void setCat_name(String cat_name) {
        this.cat_name = cat_name;
    }

    public String getCat_description() {
        return cat_description;
    }

    public void setCat_description(String cat_description) {
        this.cat_description = cat_description;
    }

    public String getSortorder() {
        return sortorder;
    }

    public void setSortorder(String sortorder) {
        this.sortorder = sortorder;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getShortname() {
        return shortname;
    }

    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    public String getIdnumber() {
        return idnumber;
    }

    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getFilepath() {
        return filepath;
    }

    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getCoursetype() {
        return coursetype;
    }

    public void setCoursetype(String coursetype) {
        this.coursetype = coursetype;
    }

    public Integer getCourse_group() {
        return course_group;
    }

    public void setCourse_group(Integer course_group) {
        this.course_group = course_group;
    }

    public Integer getRemoteid() {
        return remoteid;
    }

    public void setRemoteid(Integer remoteid) {
        this.remoteid = remoteid;
    }

    public Integer getCat_id() {
        return cat_id;
    }

    public void setCat_id(Integer cat_id) {
        this.cat_id = cat_id;
    }

    public Integer getStartdate() {
        return startdate;
    }

    public void setStartdate(Integer startdate) {
        this.startdate = startdate;
    }

    public Integer getCreated() {
        return created;
    }

    public void setCreated(Integer created) {
        this.created = created;
    }

    public Integer getModified() {
        return modified;
    }

    public void setModified(Integer modified) {
        this.modified = modified;
    }

    public Integer getLast_access() {
        return last_access;
    }

    public void setLast_access(Integer last_access) {
        this.last_access = last_access;
    }

    public Integer getEnrol_time() {
        return enrol_time;
    }

    public void setEnrol_time(Integer enrol_time) {
        this.enrol_time = enrol_time;
    }

    public Integer getTimeend() {
        return timeend;
    }

    public void setTimeend(Integer timeend) {
        this.timeend = timeend;
    }

    public Integer getTime_completed() {
        return time_completed;
    }

    public void setTime_completed(Integer time_completed) {
        this.time_completed = time_completed;
    }

    public Integer getSelf_enrolment() {
        return self_enrolment;
    }

    public void setSelf_enrolment(Integer self_enrolment) {
        this.self_enrolment = self_enrolment;
    }

    public Integer getEnroled() {
        return enroled;
    }

    public void setEnroled(Integer enroled) {
        this.enroled = enroled;
    }

    public Integer getGuest() {
        return guest;
    }

    public void setGuest(Integer guest) {
        this.guest = guest;
    }

    public Integer getCompletion_status() {
        return completion_status;
    }

    public void setCompletion_status(Integer completion_status) {
        this.completion_status = completion_status;
    }

    public static List<MyLearningOffline> getAllDataMyLearning() {
        return new Select().all()
                .from(MyLearningOffline.class)
                .execute();
    }
    public static void DeleteAllMyLearning(){
        new Delete().from(MyLearningOffline.class).execute();
    }
    public static void InsertMyLearning(CoursesObj obj){
        MyLearningOffline myLearningOffline = new MyLearningOffline();
        myLearningOffline.cat_id = obj.getCat_id();


    }
}
and in Android Manifrest 
 <meta-data android:name="AA_DB_NAME" android:value="PXLearner" />
        <meta-data android:name="AA_DB_VERSION" android:value="1" />
        <meta-data
            android:name="AA_MODELS"
            android:value="dataoffline.MyLearningOffline" />

**Comment by daothanhha** [comment]
""<meta-data android:name="AA_DB_NAME" android:value="PXLearner" />
        <meta-data android:name="AA_DB_VERSION" android:value="1" />
        <meta-data
            android:name="AA_MODELS"
            android:value="dataoffline.MyLearningOffline" />""
you can check help me, thank

**Comment by uncledoc** [comment]
what errors in the logcat?

**Comment by daothanhha** [comment]
Oke thank you verry much :D:D
