### ISSUE TITLE
Crash when save data in android 8.0

### ISSUE THREAD

**Issue by trunghau121** [pardom-zz/ActiveAndroid#535]
java.lang.SecurityException: Failed to find provider [package.Name] for user 0; expected to find a valid ContentProvider for this authority

Pls help me out this. Thanks in advance!

**Comment by agonper** [comment]
Hello @trunghau121, 

Did you figure out how to fix this? 

Some of us are having the same problem here #536 

Thanks!

**Comment by hasnain-ahmad** [comment]
Did the issue resolved...?

**Comment by agonper** [comment]
Finally, I did the switch to Android Room library and can’t be happier. Regards.
