### ISSUE TITLE
getAll() causes my app to crash. How can I fix it?

### ISSUE THREAD

**Issue by tolgasaglik** [pardom-zz/ActiveAndroid#539]
List<Item> queryItems = new ArrayList<>(getAll(String string));                       // Crash point

Function in Item class extends Model:

public static List<Item> getAll(String string) {
        return new Select()
                .from(Item.class)
                .where("String = ?")
                .orderBy("Name ASC")
                .execute();
    }

**Comment by mgautam099** [comment]
your where clause contains a question mark but you have not supplied the parameter string, try changing it to:
`where("String =?",string)`

**Comment by joshuapinter** [comment]
@tolgasaglik Did you try @mgautam099's suggestion and what was the result?
