### ISSUE TITLE
Updating table fields - leaving row id the same

### ISSUE THREAD

**Issue by barrygeehedgehoglab** [pardom-zz/ActiveAndroid#55]
Hi. 

I am trying to find a method of updating fields in a table row whilst leaving the row id (automatically generated by ActiveAndroid) the same. Is this possible in ActiveAndroid or does the row id always get updated when updates occur to a particular row?

Thanks

Barry.

**Comment by pardom-zz** [comment]
When performing an update to a SQLite row (or any SQL for that matter, as far as I know), the row id remains constant unless you explicitly update it, which is not possible in AA.
