### ISSUE TITLE
error in read and write Boolean type column

### ISSUE THREAD

**Issue by hellokent** [pardom-zz/ActiveAndroid#57]
maybe error in store boolean in INTEGER type.

**Comment by pardom-zz** [comment]
Can you be a bit more specific? Do you have logs?

**Comment by hellokent** [comment]
Yes, in my project, I fix it.
because boolean store in integer, and query by "true" or "false", "true" and "false" may be String in query in sqlite, so query would found nothing.
I solve it by query by change"true" to 1 and change"false" to 0.

**Comment by pardom-zz** [comment]
Yes, that's the correct way to do it. Here's the SQLite documentation for booleans:
https://www.sqlite.org/datatype3.html#boolean
