### ISSUE TITLE
Download Database after installation

### ISSUE THREAD

**Issue by nebulousGirl** [pardom-zz/ActiveAndroid#58]
I would like to know if it's possible to download the Database instead of packging it with the apk.

**Comment by pardom-zz** [comment]
This is something you can certainly do in code, but not something that I plan on putting into AA. I would suggest looking at the db copying code which already exists in AA, to get an idea of how to do it.

https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/DatabaseHelper.java#L85
