### ISSUE TITLE
SQL JOIN from multiple tables

### ISSUE THREAD

**Issue by mimminito** [pardom-zz/ActiveAndroid#65]
Hi,

ActiveAndroid has helped me out tremendously so far! But I have come to the point where I need to perform a JOIN across multiple Tables.

Is this possible? If so how, and what will it return?

**Comment by pardom-zz** [comment]
You can certainly do joins. Here's an example.

```
new Select()
    .from(Foo.class)
    .innerJoin(Bar.class)
    .on("Foo.Id=Bar.Id")
    .execute();
```

**Comment by mimminito** [comment]
And if I want to return columns from both tables, will ActiveAndroid allow this? I have noticed ORMLite does not allow this.

**Comment by pardom-zz** [comment]
This is not possible in AA. You could do the following to get a cursor back and manually process that.

```
From query = new Select()
    .from(Foo.class)
    .innerJoin(Bar.class)
    .on("Foo.Id=Bar.Id");

Cursor cursor = Cache.openDatabase().rawQuery(query.toSql(), query.getArguments());
```

**Comment by pardom-zz** [comment]
If you're feeling generous, you could implement a toCursor() method for the query DSL. Or I can add it to the roadmap.

**Comment by mimminito** [comment]
Thats great thanks! I didn't realise it was possible to grab the cursor back, ill give that a go. Adding it to the roadmap would be awesome.

Thanks again

**Comment by Shree9126** [comment]
new Select()
    .from(Foo.class)
    .innerJoin(Bar.class)
    .on("Foo.Id=Bar.Id")
    .execute();

if i use like this . How do create a pojo class for this return response..? Can u give any sample code. It'll be very helpful to me.
