### ISSUE TITLE
Cant seem to find the jar file.

### ISSUE THREAD

**Issue by aslakjo** [pardom-zz/ActiveAndroid#72]
Hi

Thanks for the project! Very handy.

I now wanted to update my versjon of the jar file, but cant seem to find the latest version. Or any version for that matter. It is referd to the web page and there i can only find the source. 

Any pointers or should i build it my self?

Best regards Aslak

**Comment by powerje** [comment]
I believe GitHub dropped 'downloads' support, so if the jar was hosted on GitHub previously it's likely it was taken down by a GitHub update.

**Comment by aslakjo** [comment]
That explainded it. Thanks for the reply.

I have updated the "Getting started" page. With two lines of how to run the ant command.
