### ISSUE TITLE
Can't select by Date

### ISSUE THREAD

**Issue by mikepenz** [pardom-zz/ActiveAndroid#78]
I use this awesome lib in some of my apps and had no issues til now. 

In one of my newest apps i have to select an entry by date but i'm not able to get the entry via date. even if i use the same object to do the select.

This is my select-statement. Any hints? Or is this an issue?

``` java
return new Select().from(Employment.class).where("employmentDate = ?", date).executeSingle();
```

**Comment by pardom-zz** [comment]
SQLite doesn't have a "date" type, so we must serialize it. Take a look at this to understand how it works

https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/serializer/UtilDateSerializer.java

The correct argument to pass would be date.getTime(), which returns a long
