### ISSUE TITLE
Creating new tables to existing model will not update the database

### ISSUE THREAD

**Issue by nologinatgit** [pardom-zz/ActiveAndroid#85]
I've created a database structure and my application works with that. The problem comes when I change the Model structure by adding a new Table. 
I created a new class and annotated it with the necessary tags. Unfortunately my program throws exception when I try to use that table:
_android.database.sqlite.SQLiteException: no such table: DataItems: , while compiling: SELECT \* FROM  DataItems WHERE dataId=? ORDER BY Date DESC_
**IF** I uninstall the application thus removing the database, and rerun the application, the new database structure contains the new table but this doesn't work as my clients stores data on their phones, so they will just update the program (just as I update when debug it). 
Is this intentional or a bug?

**Comment by pardom-zz** [comment]
When updating schema, you must also update the db version in the meta-data

https://github.com/pardom/ActiveAndroid/wiki/Getting-started#configuring-your-project

**Comment by nologinatgit** [comment]
Yeah, I figured it out but you should emphasize it way more in the tutorial.

**Comment by nologinatgit** [comment]
Does it work when there is already data in the database? 
I modified the schema, incremented the DB version, rerun the program but on Insert I get the following error:
_table Users has no column named Gender_
How can I force the update?
