### ISSUE TITLE
Modifying existing Table schema is not applied to database

### ISSUE THREAD

**Issue by nologinatgit** [pardom-zz/ActiveAndroid#86]
When I add a new Table to a schema and modify the DB_VERSION value in the Manifest file, it works well, the table will be created on the next run.
The problem comes when I modify an existing Table schema. My table already had data in it and I added a new Column to a table and run the program to delete the data and insert some records.. The result: the table is empty and my Insert are failing, claiming the table doesn't contain that column. I checked it, the column was missing. What should I do?

**Comment by pardom-zz** [comment]
Check out the migrations documentation.

https://github.com/pardom/ActiveAndroid/wiki/Schema-migrations
