### ISSUE TITLE
Problems when querying the DB

### ISSUE THREAD

**Issue by a0g83agbc84** [pardom-zz/ActiveAndroid#89]
Hi!

Well, I'm having problems when querying de DB using AA. The query I'm using is this one:

final String query = "query";
ArrayList<Trick> tricks_list = new Select().from(Trick.class).where("title LIKE '%?%'", query).execute();

This should work, but I get this error:

07-03 18:06:15.885: E/AndroidRuntime(20950): java.lang.IllegalArgumentException: Cannot bind argument at index 1 because the index is out of range.  The statement has 0 parameters.

I do not know what's the problem because it should work...

Thank you!

**Comment by pardom-zz** [comment]
the "?" token automatically encloses strings in single quotes. Add your wild card tokens to the argument, not the clause.

**Comment by a0g83agbc84** [comment]
Thank you!
