### ISSUE TITLE
After the latest merge, my SELECT is not working

### ISSUE THREAD

**Issue by nologinatgit** [pardom-zz/ActiveAndroid#90]
Since I updated to the latest merge (c4556f300b2bf936b8949683147b2b6c91ed238e) my working select has gone mad.

The code:
 new Select()
          .from(Results.class).where("Result='N'")
          .executeSingle();

The exception:
android.database.sqlite.SQLiteException: near "LIMIT": syntax error: , while compiling: SELECT \* FROM Results WHERE Result='N' LIMIT

What changed?

**Comment by vonloxley** [comment]
It’s a bug in #88.

**Comment by leonardoxh** [comment]
Fixed in #91

**Comment by nologinatgit** [comment]
Fix confirmed.
