### ISSUE TITLE
How to get the scripts of upgrading?

### ISSUE THREAD

**Issue by nologinatgit** [pardom-zz/ActiveAndroid#94]
As I learned, when I modify my models, the necessary things to do [are](https://github.com/pardom/ActiveAndroid/wiki/Schema-migrations):
- increase the meta-information AA_DB_VERSION.
- provide a script <NewVersion>.sql in /assets/migrations

Is there a way to get the exact script that AA creates? I know I could create a _similar_ script but I woldn't risk that especially when the model is very complex. Can I somehow get that script?

**Comment by leonardoxh** [comment]
Go in com.activeandroid.util.SQLiteUtils ans see the methods createColumnDefinition and createTableDefinition and dump the scripts from definition variable.

**Comment by nologinatgit** [comment]
I'll try, thanks for the tip.

**Comment by nologinatgit** [comment]
Dumping has worked for CREATE.
Does AA support  incremental scripts? If I change a field in a model class, can AA create ALTER scripts?

**Comment by vonloxley** [comment]
AA can’t create scripts, but you can write incremental scripts (1.sql, 2.sql, …) have a look at the wiki.

**Comment by vonloxley** [comment]
AA can’t create scripts, but you can write incremental scripts (2.sql, 3.sql, …) have a look at the wiki.

**Comment by nologinatgit** [comment]
By creating I meant the dump. I uninstalled and reinstalled the app and the CREATE queries could be dumped in the createTableDefinition method. I modified one of my models and started the app but no ALTER query was sent through AA. So I presume, only create queries are generated by AA and when I change a model class, I am responsible to create the ALTER script in the assets directory. Verify me, please.

**Comment by leonardoxh** [comment]
And if you enable the debug you can see all the scripts (on your application class) ActiveAndroid.initialize(this, true)

And the answer is yes, ActiveAndroid don't generate the Alter table scripts, when you need update the database just create a .sql file into assets/migrations with the version name like 2.sql

**Comment by nologinatgit** [comment]
If you ever plan to support ALTER, please notify me :) I close the issue now.
